<?php
$statusLabel=static fn(string $s):string=>match($s){'SEM_MENSALIDADE'=>'Sem mensalidade','EM_DIA'=>'Em dia','ATRASADA'=>'Atrasada','CANCELADA'=>'Cancelada',default=>'Pendente'};
$money=static fn(?int $v):string=>'R$ '.number_format(((int)$v)/100,2,',','.');
?>
<div class="panel-page-heading"><div><span>Financeiro</span><h1>Mensalidade do an&uacute;ncio</h1><p>Acompanhe as obriga&ccedil;&otilde;es mensais de cada an&uacute;ncio.</p></div></div>
<?php foreach($notificacoes as $n): ?><section class="panel-card"><strong><?= e($n['titulo']) ?></strong><p><?= e($n['mensagem']) ?></p></section><?php endforeach; ?>
<section class="panel-card"><div class="panel-card-heading"><h2>Situa&ccedil;&atilde;o atual</h2></div>
<?php if(!$mensalidades): ?><div class="empty-preview"><div><strong>Nenhuma mensalidade configurada</strong><p>Seus an&uacute;ncios n&atilde;o possuem cobran&ccedil;a mensal.</p></div></div><?php else: ?>
<div class="responsive-table"><table class="panel-table"><thead><tr><th>Ch&aacute;cara</th><th>Valor mensal</th><th>Status</th><th>Vencimento</th><th>Pr&oacute;xima cobran&ccedil;a</th><th></th></tr></thead><tbody>
<?php foreach($mensalidades as $m): ?><tr><td><?= e($m['chacara_nome']) ?></td><td><?= $m['ativa_flag']?$money((int)$m['valor_centavos']):'Sem mensalidade' ?></td><td><span class="status-pill"><?= e($statusLabel($m['status'])) ?></span></td><td><?= e($m['ultimo_vencimento']?date('d/m/Y',strtotime($m['ultimo_vencimento'])):'-') ?></td><td><?= e($m['proximo_vencimento']?date('d/m/Y',strtotime($m['proximo_vencimento'])):'-') ?></td><td><?php if(!empty($m['invoice_url'])&&in_array($m['status'],['PENDENTE','ATRASADA'],true)): ?><a class="btn btn-primary" href="<?= url('/proprietario/mensalidades/'.(int)$m['chacara_id'].'/pagar') ?>">Pagar / regularizar</a><?php elseif($m['ativa_flag']&&in_array($m['status'],['PENDENTE','ATRASADA'],true)): ?><small>A primeira cobran&ccedil;a est&aacute; sendo preparada. Tente novamente em instantes.</small><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endif; ?></section>
<section class="panel-card"><div class="panel-card-heading"><h2>Hist&oacute;rico de cobran&ccedil;as</h2></div><div class="responsive-table"><table class="panel-table"><thead><tr><th>Ch&aacute;cara</th><th>Valor</th><th>Status</th><th>Vencimento</th></tr></thead><tbody><?php foreach($historico as $h): ?><tr><td><?= e($h['chacara_nome']) ?></td><td><?= $money((int)$h['valor_centavos']) ?></td><td><?= e($statusLabel($h['status']==='PAGA'?'EM_DIA':$h['status'])) ?></td><td><?= e($h['vencimento']?date('d/m/Y',strtotime($h['vencimento'])):'-') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
