<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use DateTimeImmutable;use DateTimeZone;use PDO;use RuntimeException;use Throwable;
final class CancelamentoReservaService
{
 public function __construct(private?PDO$db=null){$this->db??=Database::getConnection();}
 public function cancelarUsuario(int$reservaId,int$usuarioId,?DateTimeImmutable$agora=null,?string$motivo=null):array
 {$agora??=new DateTimeImmutable('now',new DateTimeZone('America/Sao_Paulo'));$this->db->beginTransaction();try{$q=$this->db->prepare('SELECT * FROM reservas WHERE id=:r AND usuario_id=:u FOR UPDATE');$q->execute(['r'=>$reservaId,'u'=>$usuarioId]);$r=$q->fetch();if(!$r)throw new RuntimeException('Reserva nao encontrada.');if($r['status_reserva']==='cancelada'){$this->db->commit();return['status'=>'cancelada','idempotente'=>true];}if(empty($r['cancelamento_permitido_ate'])||$agora>new DateTimeImmutable((string)$r['cancelamento_permitido_ate']))throw new RuntimeException('O prazo para cancelamento desta reserva foi encerrado.');if(!in_array($r['status_reserva'],['aguardando_pagamento','confirmada'],true))throw new RuntimeException('Esta reserva nao permite cancelamento.');
  (new ReservaStatusService($this->db))->transicionar($reservaId,'cancelada',['motivo'=>$motivo,'origem'=>'cliente','responsavel_tipo'=>'cliente','responsavel_id'=>$usuarioId]);$pago=$r['status_pagamento']==='pago'||$this->pagamentoPago($reservaId);$this->db->prepare("UPDATE repasses_reservas SET status_local='cancelado',atualizado_em=CURRENT_TIMESTAMP WHERE reserva_id=:r AND status_local<>'concluido'")->execute(['r'=>$reservaId]);
  $refund=null;if($pago){$p=$this->pagamento($reservaId);$s=$this->db->prepare("INSERT INTO reembolsos_reservas(reserva_id,pagamento_id,usuario_id,valor_pago_centavos,valor_reserva_centavos,taxa_operacao_centavos,valor_reembolso_centavos,tipo,status_local,asaas_payment_id,motivo,origem) VALUES(:r,:p,:u,:vp,:vr,:t,:vr,'CANCELAMENTO_USUARIO','solicitado',:asaas,:m,'cliente') ON CONFLICT(reserva_id,tipo,valor_reembolso_centavos) DO UPDATE SET atualizado_em=reembolsos_reservas.atualizado_em RETURNING id");$s->execute(['r'=>$reservaId,'p'=>$p['id']??null,'u'=>$usuarioId,'vp'=>(int)$r['valor_total_cliente_centavos'],'vr'=>(int)$r['valor_hospedagem_centavos'],'t'=>(int)$r['taxa_operacao_pix_snapshot_centavos'],'asaas'=>$r['id_cobranca_asaas'],'m'=>mb_substr(trim((string)$motivo),0,500)]);$refund=(int)$s->fetchColumn();$this->db->prepare("INSERT INTO historico_reembolsos_reservas(reembolso_id,reserva_id,status_novo,origem,evento,motivo) SELECT :id,:r,'solicitado','cliente','CANCELAMENTO_USUARIO',:m WHERE NOT EXISTS(SELECT 1 FROM historico_reembolsos_reservas WHERE reembolso_id=:id)")->execute(['id'=>$refund,'r'=>$reservaId,'m'=>$motivo]);$this->db->prepare("UPDATE reservas SET status_pagamento='reembolso_processando' WHERE id=:r")->execute(['r'=>$reservaId]);}
  $this->db->commit();return['status'=>'cancelada','reembolso_id'=>$refund,'valor_reembolso_centavos'=>$pago?(int)$r['valor_hospedagem_centavos']:0];}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
 private function pagamentoPago(int$r):bool{$q=$this->db->prepare("SELECT EXISTS(SELECT 1 FROM pagamentos WHERE reserva_id=:r AND status_pagamento='pago')");$q->execute(['r'=>$r]);return(bool)$q->fetchColumn();}
 private function pagamento(int$r):array{$q=$this->db->prepare("SELECT * FROM pagamentos WHERE reserva_id=:r AND status_pagamento='pago' ORDER BY id DESC LIMIT 1");$q->execute(['r'=>$r]);return$q->fetch()?:[];}
}
