<?php
declare(strict_types=1);
namespace App\Services;
final class FakeAsaasClient implements AsaasClientInterface,AsaasPaymentClientInterface,AsaasTransferClientInterface
{
 public int$criacoes=0,$consultasSubcontas=0,$consultasClientes=0,$clientesCriados=0,$consultasCobrancas=0,$cobrancasCriadas=0,$consultasAssinaturas=0,$assinaturasCriadas=0,$assinaturasCanceladas=0,$transferenciasCriadas=0;public bool$simularTimeoutAposCriarAssinatura=false;public array$ultimoPayloadCobranca=[],$ultimoPayloadAssinatura=[],$ultimoPayloadTransferencia=[],$subcontasRemotas=[],$cobrancasRemotas=[],$assinaturasRemotas=[],$transferenciasRemotas=[];
 public function __construct(private array$resposta=['id'=>'acc_fake','walletId'=>'wal_fake','apiKey'=>'secret-never-persist']){}
 public function criarSubconta(array$p):array{$this->criacoes++;return$this->resposta;}public function listarSubcontas(array$f):array{$this->consultasSubcontas++;return['data'=>$this->subcontasRemotas,'totalCount'=>count($this->subcontasRemotas),'hasMore'=>false];}public function consultarSubconta(string$id):array{return['id'=>$id,'walletId'=>'wal_fake','status'=>'APPROVED'];}public function verificarContaRaiz():array{return['id'=>'root_fake','personType'=>'JURIDICA','status'=>'ACTIVE'];}
 public function listarClientes(array$f):array{$this->consultasClientes++;return['data'=>[['id'=>'cus_fake']],'totalCount'=>1];}public function criarCliente(array$p):array{$this->clientesCriados++;return['id'=>'cus_fake'];}public function listarCobrancas(array$f):array{$this->consultasCobrancas++;return['data'=>array_values(array_filter($this->cobrancasRemotas,function($x)use($f){$subscription=is_array($x['subscription']??null)?($x['subscription']['id']??''):($x['subscription']??'');return(!isset($f['externalReference'])||($x['externalReference']??'')===$f['externalReference'])&&(!isset($f['subscription'])||$subscription===$f['subscription']);}))];}public function criarCobranca(array$p):array{$this->cobrancasCriadas++;$this->ultimoPayloadCobranca=$p;return['id'=>'pay_fake','invoiceUrl'=>'https://sandbox.invalid/pay_fake','status'=>'PENDING'];}public function consultarCobranca(string$id):array{return['id'=>$id,'status'=>'PENDING'];}
 public function consultarQrCodePix(string$id):array{return['encodedImage'=>'ZmFrZQ==','payload'=>'PIX-FAKE','expirationDate'=>'2099-01-01'];}public function listarWebhooks():array{return['data'=>[]];}public function criarWebhook(array$p):array{return['id'=>'wh_fake']+$p;}public function atualizarWebhook(string$id,array$p):array{return['id'=>$id]+$p;}
 public function listarAssinaturas(array$f):array{$this->consultasAssinaturas++;return['data'=>array_values(array_filter($this->assinaturasRemotas,fn($x)=>!isset($f['externalReference'])||($x['externalReference']??'')===$f['externalReference']))];}public function criarAssinatura(array$p):array{$this->assinaturasCriadas++;$this->ultimoPayloadAssinatura=$p;$resposta=['id'=>'sub_fake','status'=>'ACTIVE','nextDueDate'=>$p['nextDueDate']??date('Y-m-d'),'externalReference'=>$p['externalReference']??null];if($this->simularTimeoutAposCriarAssinatura){$this->assinaturasRemotas[]=$resposta;$this->simularTimeoutAposCriarAssinatura=false;throw new AsaasTimeoutException('Timeout simulado apos criacao remota.');}return$resposta;}public function atualizarAssinatura(string$id,array$p):array{$this->ultimoPayloadAssinatura=$p;return['id'=>$id,'status'=>'ACTIVE']+$p;}public function cancelarAssinatura(string$id):array{$this->assinaturasCanceladas++;return['id'=>$id,'deleted'=>true];}
 public function listarTransferencias(array$f):array{return['data'=>array_values(array_filter($this->transferenciasRemotas,fn($x)=>!isset($f['externalReference'])||($x['externalReference']??'')===$f['externalReference']))];}public function criarTransferencia(array$p):array{$this->transferenciasCriadas++;$this->ultimoPayloadTransferencia=$p;return['id'=>'tra_fake','status'=>'PENDING'];}public function consultarTransferencia(string$id):array{return['id'=>$id,'status'=>'PENDING'];}
}
