<?php
declare(strict_types=1);
namespace App\Models;
use App\Core\Model;use RuntimeException;use Throwable;
final class ConfiguracaoFinanceira extends Model
{
 public function atual():?array{$c=$this->db->query('SELECT * FROM configuracoes_financeiras WHERE vigencia_fim IS NULL ORDER BY versao DESC LIMIT 1')->fetch();if(!$c)return null;$s=$this->db->prepare('SELECT * FROM taxas_meios_pagamento WHERE configuracao_financeira_id=:id ORDER BY forma_pagamento,quantidade_parcelas');$s->execute(['id'=>$c['id']]);$c['taxas']=$s->fetchAll();return$c;}
 public function historico():array{return$this->db->query('SELECT h.*,u.nome administrador_nome FROM historico_configuracoes_financeiras h JOIN usuarios u ON u.id=h.administrador_id ORDER BY h.criado_em DESC,h.id DESC LIMIT 50')->fetchAll();}
 public function salvarOperacaoPix(int$taxa,int$admin,string$motivo):int
 {if($taxa<0)throw new RuntimeException('Taxa de operacao PIX invalida.');$motivo=trim($motivo);if($motivo==='')throw new RuntimeException('Informe o motivo da alteracao.');$this->db->beginTransaction();try{$anterior=$this->atual();$v=(int)$this->db->query('SELECT COALESCE(MAX(versao),0)+1 FROM configuracoes_financeiras')->fetchColumn();$this->db->exec('UPDATE configuracoes_financeiras SET vigencia_fim=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE vigencia_fim IS NULL');$s=$this->db->prepare('INSERT INTO configuracoes_financeiras(taxa_plataforma_percentual_bps,taxa_plataforma_fixa_centavos,taxa_operacao_pix_reserva_centavos,precificacao_ativa,versao,criado_por_admin_id) VALUES(0,0,:taxa,TRUE,:v,:a) RETURNING id');$s->execute(['taxa'=>$taxa,'v'=>$v,'a'=>$admin]);$id=(int)$s->fetchColumn();$this->db->prepare("INSERT INTO taxas_meios_pagamento(configuracao_financeira_id,forma_pagamento,quantidade_parcelas,percentual_gateway_bps,taxa_fixa_gateway_centavos,margem_seguranca_bps,ativo) VALUES(:id,'PIX',1,0,0,0,TRUE)")->execute(['id'=>$id]);$nova=$this->atual();$this->db->prepare('INSERT INTO historico_configuracoes_financeiras(configuracao_anterior,configuracao_nova,administrador_id,motivo,versao) VALUES(CAST(:a AS JSONB),CAST(:n AS JSONB),:admin,:m,:v)')->execute(['a'=>$anterior?json_encode($anterior):null,'n'=>json_encode($nova),'admin'=>$admin,'m'=>mb_substr($motivo,0,500),'v'=>$v]);$this->db->commit();return$v;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
