<?php
declare(strict_types=1);
namespace App\Models;
use App\Core\Model;use PDO;
final class FinanceiroProprietario extends Model
{
 public function buscar(int $pid):?array{$s=$this->db->prepare('SELECT * FROM proprietario_dados_financeiros WHERE proprietario_id=:id');$s->execute(['id'=>$pid]);return$s->fetch()?:null;}
 public function salvar(int $pid,array $d,int $uid):void{$old=$this->buscar($pid);$sql='INSERT INTO proprietario_dados_financeiros (proprietario_id,tipo_pessoa,cpf_cnpj,nome_razao_social,nome_fantasia,data_nascimento,tipo_empresa,renda_faturamento_mensal_centavos,telefone,celular,email_financeiro,cep,endereco,numero,complemento,bairro,cidade,estado,dados_completos,validado_em) VALUES (:pid,:tipo,:doc,:nome,:fantasia,:nascimento,:empresa,:renda,:telefone,:celular,:email,:cep,:endereco,:numero,:complemento,:bairro,:cidade,:estado,TRUE,CURRENT_TIMESTAMP) ON CONFLICT(proprietario_id) DO UPDATE SET tipo_pessoa=EXCLUDED.tipo_pessoa,cpf_cnpj=EXCLUDED.cpf_cnpj,nome_razao_social=EXCLUDED.nome_razao_social,nome_fantasia=EXCLUDED.nome_fantasia,data_nascimento=EXCLUDED.data_nascimento,tipo_empresa=EXCLUDED.tipo_empresa,renda_faturamento_mensal_centavos=EXCLUDED.renda_faturamento_mensal_centavos,telefone=EXCLUDED.telefone,celular=EXCLUDED.celular,email_financeiro=EXCLUDED.email_financeiro,cep=EXCLUDED.cep,endereco=EXCLUDED.endereco,numero=EXCLUDED.numero,complemento=EXCLUDED.complemento,bairro=EXCLUDED.bairro,cidade=EXCLUDED.cidade,estado=EXCLUDED.estado,dados_completos=TRUE,validado_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP';
  $this->db->beginTransaction();$this->db->prepare($sql)->execute(['pid'=>$pid,'tipo'=>$d['tipo_pessoa'],'doc'=>$d['cpf_cnpj'],'nome'=>$d['nome_razao_social'],'fantasia'=>$d['nome_fantasia']?:null,'nascimento'=>$d['data_nascimento']?:null,'empresa'=>$d['tipo_empresa']?:null,'renda'=>$d['renda_faturamento_mensal_centavos'],'telefone'=>$d['telefone']?:null,'celular'=>$d['celular'],'email'=>$d['email_financeiro'],'cep'=>$d['cep'],'endereco'=>$d['endereco'],'numero'=>$d['numero'],'complemento'=>$d['complemento']?:null,'bairro'=>$d['bairro'],'cidade'=>$d['cidade'],'estado'=>$d['estado']]);
  $fields=[];foreach($d as$k=>$v)if(($old[$k]??null)!=$v)$fields[]=$k;$this->db->prepare('INSERT INTO auditoria_dados_financeiros(proprietario_id,usuario_id,origem,campos_alterados) VALUES(:p,:u,:o,CAST(:f AS jsonb))')->execute(['p'=>$pid,'u'=>$uid,'o'=>'proprietario','f'=>json_encode($fields)]);$this->db->commit();}
 public function aceiteVigente(int $pid):bool{$s=$this->db->prepare("SELECT EXISTS(SELECT 1 FROM aceites_financeiros_proprietarios WHERE proprietario_id=:p AND tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND revogado_em IS NULL)");$s->execute(['p'=>$pid]);return(bool)$s->fetchColumn();}
 public function aceitar(int $pid,string $hash,string $ip,string $ua):void{$this->db->prepare("INSERT INTO aceites_financeiros_proprietarios(proprietario_id,tipo_aceite,versao_documento,texto_hash,ip,user_agent_resumido) VALUES(:p,'ONBOARDING_ASAAS_NON_BAAS','operacional-v1-revisao-juridica-pendente',:h,:ip,:ua) ON CONFLICT DO NOTHING")->execute(['p'=>$pid,'h'=>$hash,'ip'=>mb_substr($ip,0,45),'ua'=>mb_substr($ua,0,255)]);}
 public function subconta(int $pid,string $amb='sandbox'):?array{$s=$this->db->prepare('SELECT * FROM asaas_subcontas WHERE proprietario_id=:p AND ambiente=:a');$s->execute(['p'=>$pid,'a'=>$amb]);return$s->fetch()?:null;}
 public function listarAdmin(string $status=''):array{$expr="CASE WHEN s.id IS NOT NULL THEN s.status_local WHEN d.id IS NULL OR NOT d.dados_completos THEN 'dados_incompletos' WHEN a.id IS NULL THEN 'aguardando_aceite' ELSE 'pronto_para_criacao' END";$where=$status!==''?"WHERE ($expr)=:status":'';$s=$this->db->prepare("SELECT p.id,p.nome,p.email,$expr status_local,s.asaas_account_id,s.asaas_wallet_id,s.ultima_sincronizacao_em FROM proprietarios p LEFT JOIN proprietario_dados_financeiros d ON d.proprietario_id=p.id LEFT JOIN aceites_financeiros_proprietarios a ON a.proprietario_id=p.id AND a.tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND a.revogado_em IS NULL LEFT JOIN asaas_subcontas s ON s.proprietario_id=p.id AND s.ambiente='sandbox' $where ORDER BY p.id DESC");$s->execute($status!==''?['status'=>$status]:[]);return$s->fetchAll(PDO::FETCH_ASSOC);}
}
