<?php

declare(strict_types=1);

require dirname(__DIR__).'/scripts/bootstrap.php';

use App\Core\Database;
use App\Models\Affiliate;
use App\Services\AffiliatePortalService;

$db=Database::getConnection();if($db->query('SELECT current_database()')->fetchColumn()!=='alugfacil_dev')throw new RuntimeException('Teste permitido somente em alugfacil_dev.');
$ok=0;$fail=0;$check=static function(string$name,bool$condition)use(&$ok,&$fail):void{echo($condition?'[OK] ':'[FALHA] ').$name.PHP_EOL;$condition?$ok++:$fail++;};$tag=(string)random_int(10000000,99999999);$db->beginTransaction();
try{
    $u=$db->prepare("INSERT INTO usuarios(nome,email,senha_hash,tipo_usuario,status) VALUES(:nome,:email,'hash',:tipo,'ativo') RETURNING id");$u->execute(['nome'=>'Admin Portal','email'=>'admin.portal.'.$tag.'@test.local','tipo'=>'admin']);$admin=(int)$u->fetchColumn();
    $affiliateInsert=$db->prepare("INSERT INTO afiliados(nome,cpf_cnpj,telefone,email,senha_hash,chave_pix,tipo_chave_pix,status) VALUES(:nome,:doc,'11999999999',:email,:senha,:pix,'aleatoria','ativo') RETURNING id,codigo");
    $affiliateInsert->execute(['nome'=>'Afiliado Portal A','doc'=>'39053344705','email'=>'portal.a.'.$tag.'@test.local','senha'=>password_hash('SenhaAtual123',PASSWORD_DEFAULT),'pix'=>'pix-a-'.$tag]);$affiliateA=$affiliateInsert->fetch();
    $affiliateInsert->execute(['nome'=>'Afiliado Portal B','doc'=>'52998224725','email'=>'portal.b.'.$tag.'@test.local','senha'=>password_hash('SenhaAtual123',PASSWORD_DEFAULT),'pix'=>'pix-b-'.$tag]);$affiliateB=$affiliateInsert->fetch();
    $affiliateInsert->execute(['nome'=>'Afiliado Portal Vazio','doc'=>'11144477735','email'=>'portal.empty.'.$tag.'@test.local','senha'=>password_hash('SenhaAtual123',PASSWORD_DEFAULT),'pix'=>'pix-empty-'.$tag]);$affiliateEmpty=$affiliateInsert->fetch();
    $ownerIds=[];$propertyIds=[];$monthlyIds=[];$chargeIds=[];
    $makeOwner=function(int$affiliate,string$name,string$origin)use($db,$u,$tag,&$ownerIds):int{$email=strtolower(str_replace(' ','',$name)).'.'.$tag.'@test.local';$u->execute(['nome'=>$name,'email'=>$email,'tipo'=>'proprietario']);$uid=(int)$u->fetchColumn();$s=$db->prepare("INSERT INTO proprietarios(usuario_id,nome,telefone,email,status,afiliado_id,afiliado_origem,afiliado_atribuido_em) VALUES(:u,:n,'11988887777',:e,'ativo',:a,:o,'2026-08-01 10:00:00-03') RETURNING id");$s->execute(['u'=>$uid,'n'=>$name,'e'=>$email,'a'=>$affiliate,'o'=>$origin]);$id=(int)$s->fetchColumn();$ownerIds[]=$id;return$id;};
    $ownerA=$makeOwner((int)$affiliateA['id'],'Proprietario Codigo','codigo');$ownerB=$makeOwner((int)$affiliateA['id'],'Proprietario Link','link');$foreignOwner=$makeOwner((int)$affiliateB['id'],'Proprietario Outro','codigo');
    $makeProperty=function(int$owner,string$name)use($db,$tag,&$propertyIds,&$monthlyIds,&$chargeIds):array{$s=$db->prepare("INSERT INTO chacaras(proprietario_id,nome,valor_diaria,cidade,estado,endereco,status,status_aprovacao,status_operacional) VALUES(:o,:n,100,'Campinas','SP','Rua Portal','disponivel','aprovada','disponivel') RETURNING id");$s->execute(['o'=>$owner,'n'=>$name]);$property=(int)$s->fetchColumn();$propertyIds[]=$property;$s=$db->prepare("INSERT INTO mensalidades_anuncios(chacara_id,proprietario_id,ativa,valor_centavos,status,asaas_subscription_id) VALUES(:c,:o,TRUE,10000,'EM_DIA',:sub) RETURNING id");$s->execute(['c'=>$property,'o'=>$owner,'sub'=>'sub_portal_'.$property.'_'.$tag]);$monthly=(int)$s->fetchColumn();$monthlyIds[]=$monthly;$s=$db->prepare("INSERT INTO cobrancas_mensalidades(mensalidade_id,asaas_payment_id,valor_centavos,status,pago_em) VALUES(:m,:pay,10000,'PAGA','2026-08-01 12:00:00-03') RETURNING id");$s->execute(['m'=>$monthly,'pay'=>'pay_portal_'.$property.'_'.$tag]);$charge=(int)$s->fetchColumn();$chargeIds[]=$charge;return[$property,$monthly,$charge];};
    [$chacaraA1,$mensalA1,$chargeA1]=$makeProperty($ownerA,'Chacara A1');[$chacaraA2,$mensalA2,$chargeA2]=$makeProperty($ownerA,'Chacara A2');[$chacaraB1,$mensalB1,$chargeB1]=$makeProperty($ownerB,'Chacara B1');[$foreignProperty]=$makeProperty($foreignOwner,'Chacara Estrangeira');
    $commissionInsert=$db->prepare("INSERT INTO comissoes_afiliados(afiliado_id,proprietario_id,chacara_id,mensalidade_id,cobranca_mensalidade_id,asaas_payment_id,valor_base_centavos,percentual_bps,valor_comissao_centavos,confirmado_em,disponivel_em,status,estornada_em) VALUES(:a,:o,:c,:m,:charge,:pay,10000,1000,:value,:confirmed,CAST(:confirmed AS TIMESTAMPTZ)+INTERVAL '7 days',:status,:reversed) RETURNING id");
    $commissionInsert->execute(['a'=>$affiliateA['id'],'o'=>$ownerA,'c'=>$chacaraA1,'m'=>$mensalA1,'charge'=>$chargeA1,'pay'=>'commission_open_'.$tag,'value'=>1000,'confirmed'=>'2026-08-19 12:00:00-03','status'=>'EM_ABERTO','reversed'=>null]);$openCommission=(int)$commissionInsert->fetchColumn();
    $commissionInsert->execute(['a'=>$affiliateA['id'],'o'=>$ownerA,'c'=>$chacaraA2,'m'=>$mensalA2,'charge'=>$chargeA2,'pay'=>'commission_reversed_'.$tag,'value'=>2000,'confirmed'=>'2026-08-01 12:00:00-03','status'=>'ESTORNADA','reversed'=>'2026-08-15 12:00:00-03']);$reversedCommission=(int)$commissionInsert->fetchColumn();
    $commissionInsert->execute(['a'=>$affiliateA['id'],'o'=>$ownerB,'c'=>$chacaraB1,'m'=>$mensalB1,'charge'=>$chargeB1,'pay'=>'commission_available_'.$tag,'value'=>3000,'confirmed'=>'2026-08-01 13:00:00-03','status'=>'EM_ABERTO','reversed'=>null]);$availableCommission=(int)$commissionInsert->fetchColumn();
    $extraCharge=$db->prepare("INSERT INTO cobrancas_mensalidades(mensalidade_id,asaas_payment_id,valor_centavos,status,pago_em) VALUES(:m,:pay,10000,'PAGA','2026-08-02 12:00:00-03') RETURNING id");$extraCharge->execute(['m'=>$mensalA1,'pay'=>'pay_portal_extra_'.$tag]);$extraChargeId=(int)$extraCharge->fetchColumn();
    $commissionInsert->execute(['a'=>$affiliateA['id'],'o'=>$ownerA,'c'=>$chacaraA1,'m'=>$mensalA1,'charge'=>$extraChargeId,'pay'=>'commission_paid_'.$tag,'value'=>4000,'confirmed'=>'2026-08-02 12:00:00-03','status'=>'PAGA','reversed'=>null]);$paidCommission=(int)$commissionInsert->fetchColumn();
    $paymentInsert=$db->prepare("INSERT INTO pagamentos_afiliados(afiliado_id,valor_centavos,data_pagamento,referencia,observacao,administrador_id) VALUES(:a,:v,'2026-08-15',:r,'observacao interna nao exibir',:admin) RETURNING id");$paymentInsert->execute(['a'=>$affiliateA['id'],'v'=>1000,'r'=>'PIX parcial','admin'=>$admin]);$partialPayment=(int)$paymentInsert->fetchColumn();$paymentInsert->execute(['a'=>$affiliateA['id'],'v'=>4000,'r'=>'PIX integral','admin'=>$admin]);$fullPayment=(int)$paymentInsert->fetchColumn();
    $allocation=$db->prepare('INSERT INTO alocacoes_pagamentos_afiliados(pagamento_afiliado_id,comissao_afiliado_id,valor_centavos) VALUES(:p,:c,:v)');$allocation->execute(['p'=>$partialPayment,'c'=>$reversedCommission,'v'=>1000]);$allocation->execute(['p'=>$fullPayment,'c'=>$paidCommission,'v'=>4000]);
    $db->prepare("INSERT INTO ajustes_afiliados(afiliado_id,comissao_afiliado_id,tipo,valor_centavos,motivo) VALUES(:a,:c,'ESTORNO_COMISSAO_PAGA',-1000,'evento tecnico privado')")->execute(['a'=>$affiliateA['id'],'c'=>$reversedCommission]);
    $portal=new AffiliatePortalService($db);$now=new DateTimeImmutable('2026-08-20 12:00:00-03');$dashboard=$portal->dashboard((int)$affiliateA['id'],$now);
    $check('01 dashboard integrado conta dois proprietarios e tres chacaras',$dashboard['proprietarios']===2&&$dashboard['chacaras']===3&&$dashboard['chacaras_mensalidade']===3);
    $check('02 dashboard usa comissoes reais do mes',$dashboard['pagamentos_mes']===4&&$dashboard['comissao_mes_centavos']===10000);
    $check('03 dashboard reutiliza ledger para aberto disponivel recebido e ajuste',$dashboard['em_aberto_centavos']===1000&&$dashboard['saldo_disponivel_centavos']===2000&&$dashboard['total_pago_centavos']===5000&&$dashboard['ajustes_centavos']===-1000);
    $empty=$portal->dashboard((int)$affiliateEmpty['id'],$now);$check('04 afiliado sem indicacoes retorna indicadores reais zerados',$empty['proprietarios']===0&&$empty['chacaras']===0&&$empty['comissao_mes_centavos']===0&&$empty['saldo_disponivel_centavos']===0);
    $owners=$portal->referredOwners((int)$affiliateA['id']);$check('05 indicados isola afiliado e agrega sem N mais um',count($owners['items'])===2&&array_sum(array_map('intval',array_column($owners['items'],'chacaras')))===3);
    $byName=$portal->referredOwners((int)$affiliateA['id'],['nome'=>'Codigo']);$byEmail=$portal->referredOwners((int)$affiliateA['id'],['email'=>'proprietariolink']);$check('06 filtros de nome e email funcionam',$byName['total']===1&&$byEmail['total']===1);
    $pageTwo=$portal->referredOwners((int)$affiliateA['id'],[],2,1);$check('06a paginacao preserva totais e limita a pagina',$pageTwo['total']===2&&$pageTwo['page']===2&&$pageTwo['pages']===2&&count($pageTwo['items'])===1);
    $origins=array_column($owners['items'],'afiliado_origem');sort($origins);$check('07 origens link e codigo permanecem disponiveis para rotulo amigavel',$origins===['codigo','link']);
    $ownerDetail=$portal->referredOwner((int)$affiliateA['id'],$ownerA);$check('08 detalhe mostra duas chacaras e comissao liquida correta',$ownerDetail!==null&&count($ownerDetail['chacaras_lista'])===2&&(int)$ownerDetail['comissao_centavos']===4000);
    $check('09 IDOR de proprietario pertencente a outro afiliado retorna inexistente',$portal->referredOwner((int)$affiliateB['id'],$ownerA)===null&&$portal->referredOwner((int)$affiliateA['id'],$foreignOwner)===null);
    $propertyTotals=array_column($ownerDetail['chacaras_lista'],'comissao_centavos','nome');$check('10 comissao por chacara usa ledger e nao mensalidade',(int)$propertyTotals['Chacara A1']===5000&&(int)$propertyTotals['Chacara A2']===-1000);
    $allCommissions=$portal->commissions((int)$affiliateA['id'],[],1,30,$now);$open=$portal->commissions((int)$affiliateA['id'],['status'=>'EM_ABERTO'],1,30,$now);$available=$portal->commissions((int)$affiliateA['id'],['status'=>'DISPONIVEL'],1,30,$now);$paid=$portal->commissions((int)$affiliateA['id'],['status'=>'PAGA'],1,30,$now);$reversed=$portal->commissions((int)$affiliateA['id'],['status'=>'ESTORNADA'],1,30,$now);
    $check('11 historico apresenta aberto disponivel paga e estornada',$allCommissions['total']===4&&$open['total']===1&&$available['total']===1&&$paid['total']===1&&$reversed['total']===1);
    $period=$portal->commissions((int)$affiliateA['id'],['de'=>'2026-08-19','ate'=>'2026-08-19'],1,30,$now);$propertyFilter=$portal->commissions((int)$affiliateA['id'],['chacara'=>'B1'],1,30,$now);$check('12 filtros de periodo e chacara funcionam',$period['total']===1&&$propertyFilter['total']===1);
    $dto=json_encode([$dashboard,$owners,$ownerDetail,$allCommissions,$portal->receivedPayments((int)$affiliateA['id']),$portal->adjustments((int)$affiliateA['id'])],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$views=(string)file_get_contents(dirname(__DIR__).'/app/views/afiliado/comissoes.php').(string)file_get_contents(dirname(__DIR__).'/app/views/afiliado/indicado_detalhe.php');
    $check('13 DTO e views nao expoem senha hash Asaas ou base da mensalidade',!str_contains($dto,'senha')&&!str_contains($dto,'asaas_payment_id')&&!str_contains($dto,'valor_base_centavos')&&!str_contains($views,'asaas_payment_id')&&!str_contains($views,'valor_base_centavos')&&!str_contains($views,'valor_centavos AS mensalidade'));
    $payments=$portal->receivedPayments((int)$affiliateA['id']);$check('14 pagamento recebido omite observacao administrativa',count($payments)===2&&!array_key_exists('observacao',$payments[0]));
    $adjustments=$portal->adjustments((int)$affiliateA['id']);$check('15 ajuste omite evento e motivo tecnico',count($adjustments)===1&&!array_key_exists('asaas_event_id',$adjustments[0])&&!array_key_exists('motivo',$adjustments[0]));
    $model=new Affiliate();$before=$model->findById((int)$affiliateA['id']);$model->updateOwnProfile((int)$affiliateA['id'],['nome'=>'Afiliado Atualizado','telefone'=>'11977776666','email'=>'portal.atualizado.'.$tag.'@test.local','chave_pix'=>'nova-pix-'.$tag,'tipo_chave_pix'=>'aleatoria','banco'=>'Banco Teste'],'NovaSenha123');$after=$model->findById((int)$affiliateA['id']);$credentials=$model->findWithPasswordById((int)$affiliateA['id']);
    $check('16 perfil edita somente campos permitidos e senha segura',$after['nome']==='Afiliado Atualizado'&&$after['codigo']===$before['codigo']&&$after['status']===$before['status']&&$after['cpf_cnpj']===$before['cpf_cnpj']&&password_verify('NovaSenha123',$credentials['senha_hash']));
    $controller=(string)file_get_contents(dirname(__DIR__).'/app/controllers/AffiliateController.php');$routes=(string)file_get_contents(dirname(__DIR__).'/app/config/routes.php');$sidebar=(string)file_get_contents(dirname(__DIR__).'/app/views/layouts/sidebar_afiliado.php');$profileView=(string)file_get_contents(dirname(__DIR__).'/app/views/afiliado/perfil.php');
    $check('17 todas as rotas usam sessao autenticada e perfil usa CSRF',substr_count($controller,'AffiliateAuth::requireLogin()')>=5&&str_contains($controller,'verify_csrf()')&&str_contains($profileView,'csrf_field()'));
    $check('18 navegador nunca fornece affiliate_id ao portal',!str_contains($controller,'$_GET[\'affiliate_id\']')&&!str_contains($controller,'$_POST[\'affiliate_id\']')&&str_contains($controller,'(int)$affiliate[\'id\']'));
    $check('19 perfil ignora codigo status documento e percentual enviados',!preg_match('/\$_POST\[\'(?:codigo|status|cpf_cnpj|percentual)\'\]/',$controller));
    $check('20 menu final possui dashboard indicados comissoes perfil e logout',str_contains($sidebar,'/afiliado/indicados')&&str_contains($sidebar,'/afiliado/comissoes')&&str_contains($sidebar,'/afiliado/perfil')&&str_contains($sidebar,'/afiliado/logout')&&!str_contains($sidebar,'sidebar-placeholder'));
    $check('21 portal e somente leitura financeira',!preg_match("#post\('/afiliado/(?:comissoes|pagamentos|ajustes)#",$routes)&&!str_contains($controller,'registerManualPayment'));
}finally{if($db->inTransaction())$db->rollBack();}
echo 'Total: '.($ok+$fail)." | Aprovados: $ok | Falhos: $fail".PHP_EOL;exit($fail?1:0);
