<?php
declare(strict_types=1);
require dirname(__DIR__).'/scripts/bootstrap.php';
use App\Core\Database;
use App\Services\AsaasEnvironment;
use App\Services\AsaasTimeoutException;
use App\Services\AsaasSubaccountVault;
use App\Services\FinancialOperationService;
if(getenv('DB_NAME')!=='alugfacil_dev'||!in_array(getenv('DB_HOST'),['127.0.0.1','localhost','::1'],true))throw new RuntimeException('Somente banco local.');
$db=Database::getConnection();$scope='fixture-'.bin2hex(random_bytes(6));$service=new FinancialOperationService($scope,$db);
$check=static function(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);echo '[OK] '.$message.PHP_EOL;};
$reject=static function(callable $f,string $message)use($check):void{try{$f();}catch(PDOException $e){throw $e;}catch(RuntimeException){$check(true,$message);return;}throw new RuntimeException($message);};
$oldApp=getenv('APP_ENV');$oldEnv=getenv('ASAAS_ENVIRONMENT');$oldUrl=getenv('ASAAS_BASE_URL');
try {
    putenv('APP_ENV=production');$check(AsaasEnvironment::config()['environment']==='sandbox','APP_ENV production independente do gateway Sandbox');
    putenv('ASAAS_BASE_URL=https://api-sandbox.asaas.com.attacker.invalid/v3');$reject(fn()=>AsaasEnvironment::config(),'Host parecido rejeitado');
    putenv('ASAAS_BASE_URL=https://api-sandbox.asaas.com/v3?proxy=1');$reject(fn()=>AsaasEnvironment::config(),'Query no host base rejeitada');
    putenv('ASAAS_BASE_URL='.$oldUrl);putenv('ASAAS_ENVIRONMENT=production');$reject(fn()=>AsaasEnvironment::config(),'Production permanece bloqueado');putenv('ASAAS_ENVIRONMENT='.$oldEnv);
    $posts=0;$payload=['amount'=>12345,'document'=>'synthetic'];
    $create=function(string $ref,array $p)use(&$posts,$db,$check):array{$posts++;$q=$db->prepare('SELECT estado FROM operacoes_financeiras WHERE referencia=:r');$q->execute(['r'=>$ref]);$check($q->fetchColumn()==='executando'&&!$db->inTransaction(),'Intencao duravel antes da chamada externa');return ['id'=>'fake-'.$posts,'status'=>'PENDING','apiKey'=>'must-not-persist'];};
    $one=$service->executar('customer','one',1,$payload,fn()=>[],$create);
    $two=$service->executar('customer','one',1,array_reverse($payload,true),fn()=>[],$create);
    $check($posts===1&&$one['id']===$two['id'],'Repeticao e ordem das chaves nao duplicam POST');
    $check(!isset($one['apiKey']),'Resposta persistida exclui API key');
    $reject(fn()=>$service->executar('customer','one',1,['amount'=>999],fn()=>[],$create),'Payload alterado de intencao existente bloqueado');
    $calls=0;$timeout=function()use(&$calls){$calls++;throw new AsaasTimeoutException('simulated');};
    $reject(fn()=>$service->executar('transferencia','unknown',1,['value'=>100],fn()=>[],$timeout),'Timeout gera resultado desconhecido');
    $reject(fn()=>$service->executar('transferencia','unknown',1,['value'=>100],fn()=>[],$timeout),'GET vazio nao permite repetir POST desconhecido');
    $check($calls===1,'Timeout nunca gerou segundo POST');
    $q=$db->prepare("SELECT estado,erro_codigo FROM operacoes_financeiras WHERE conta_gateway=:s AND entidade='unknown'");$q->execute(['s'=>$scope]);$unknown=$q->fetch();
    $check($unknown['estado']==='desconhecida'&&$unknown['erro_codigo']==='RESULTADO_DESCONHECIDO','Estado desconhecido persistido apos timeout');
    $refusals=0;
    $refuse=function()use(&$refusals){$refusals++;throw new App\Services\AsaasApiException('synthetic refusal',422);};
    $reject(fn()=>$service->executar('subconta','refused',1,[],fn()=>[],$refuse),'Recusa HTTP conhecida tratada sem erro PostgreSQL');
    $q=$db->prepare("SELECT estado,http_status,proxima_tentativa_em FROM operacoes_financeiras WHERE conta_gateway=:s AND entidade='refused'");$q->execute(['s'=>$scope]);$refused=$q->fetch();
    $check($refused['estado']==='recusada'&&(int)$refused['http_status']===422&&$refused['proxima_tentativa_em']===null,'Recusa definitiva nao agenda retry automatico');
    $reject(fn()=>$service->executar('subconta','refused',1,[],fn()=>[],$refuse),'Recusa definitiva impede novo envio da mesma obrigacao');
    $check($refusals===1,'POST recusado definitivamente nao e repetido');
    $limited=0;$limit=function()use(&$limited){$limited++;throw new App\Services\AsaasApiException('rate limit',429);};
    $reject(fn()=>$service->executar('customer','limited',1,[],fn()=>[],$limit),'HTTP 429 registra limite temporario');
    $q=$db->prepare("SELECT proxima_tentativa_em > clock_timestamp() FROM operacoes_financeiras WHERE conta_gateway=:s AND entidade='limited'");$q->execute(['s'=>$scope]);$check((bool)$q->fetchColumn(),'Limite temporario agenda retry');
    $reject(fn()=>$service->executar('customer','limited',1,[],fn()=>[],$limit),'Limite temporario respeita intervalo');
    $check($limited===1,'Intervalo impede segundo POST antecipado');
    $resolved=$service->executar('transferencia','unknown',1,['value'=>100],fn()=>[['id'=>'recovered','status'=>'DONE']],$timeout);
    $check($resolved['id']==='recovered'&&$calls===1,'Reconciliacao recupera o resultado externo');
    $reject(fn()=>$service->executar('customer','many',1,[],fn()=>[['id'=>'a'],['id'=>'b']],$create),'Multiplas correspondencias ficam em conciliacao');
    $reject(fn()=>$service->executar('checkout','secret',1,['creditCard'=>['number'=>'synthetic']],fn()=>[],$create),'Dados de cartao proibidos na intencao');
    $reject(fn()=>$service->executar('checkout','header-secret',1,['headers'=>['Authorization'=>'synthetic-private']],fn()=>[],$create),'Authorization proibido na intencao antes de persistir');
    $reject(fn()=>$service->executar('checkout','proxy-secret',1,['headers'=>['Proxy-Authorization'=>'synthetic-private']],fn()=>[],$create),'Proxy-Authorization proibido na intencao antes de persistir');
    $config=require APP_ROOT.'/app/config/database.php';
    $other=new PDO('pgsql:host='.$config['DB_HOST'].';port='.$config['DB_PORT'].';dbname='.$config['DB_NAME'],$config['DB_USER'],$config['DB_PASS'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_STATEMENT_CLASS=>[App\Core\TypedStatement::class]]);
    $contender=new FinancialOperationService($scope,$other);$competingPosts=0;
    $service->executar('checkout','race',1,[],fn()=>[],function()use($contender,$reject,&$competingPosts):array{$reject(fn()=>$contender->executar('checkout','race',1,[],fn()=>[],function()use(&$competingPosts){$competingPosts++;return ['id'=>'duplicate'];}),'Segunda conexao PostgreSQL nao reivindica operacao em andamento');return ['id'=>'winner'];});
    $check($competingPosts===0,'Concorrencia nao faz chamada externa duplicada');
    AsaasSubaccountVault::save($scope,'account','fixture-secret');
    $check(AsaasSubaccountVault::load($scope,'account')==='fixture-secret','Cofre AES-256-GCM recupera segredo');
    $q=$db->prepare("SELECT segredo_cifrado FROM asaas_subconta_credenciais WHERE conta_gateway=:s");$q->execute(['s'=>$scope]);$cipher=$q->fetchColumn();$check(!str_contains($cipher,'fixture-secret'),'Segredo nao armazenado em texto simples');
    $db->prepare('UPDATE asaas_subconta_credenciais SET asaas_account_id=:a WHERE conta_gateway=:s')->execute(['a'=>'tampered','s'=>$scope]);
    $reject(fn()=>AsaasSubaccountVault::load($scope,'tampered'),'Troca de titular do ciphertext invalida autenticacao');
}finally {
    putenv('APP_ENV='.$oldApp);putenv('ASAAS_ENVIRONMENT='.$oldEnv);putenv('ASAAS_BASE_URL='.$oldUrl);
    $db->prepare('DELETE FROM tentativas_operacoes_financeiras WHERE operacao_id IN (SELECT id FROM operacoes_financeiras WHERE conta_gateway=:s)')->execute(['s'=>$scope]);
    $db->prepare('DELETE FROM operacoes_financeiras WHERE conta_gateway=:s')->execute(['s'=>$scope]);
    $db->prepare('DELETE FROM asaas_subconta_credenciais WHERE conta_gateway=:s')->execute(['s'=>$scope]);
}
echo "Fase 3: idempotencia, concorrencia e cofre verificados sem chamadas financeiras reais.\n";
