import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

test('API local real: cadastro, perfil, logout, login e retorno seguro', async ({ page, request }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const email = `mobile-etapa4-${randomBytes(6).toString('hex')}@teste.invalid`;
  const password = randomBytes(16).toString('hex');
  const evidence = resolve('../storage/screenshots/mobile-etapa4'); await mkdir(evidence, { recursive: true });
  const identitiesPath = resolve(evidence, 'fixture-identities.json');
  const identities: string[] = JSON.parse(await readFile(identitiesPath, 'utf8').catch(() => '[]'));
  await writeFile(identitiesPath, JSON.stringify([...identities, email]));
  await page.goto('/');
  await expect(page.getByRole('textbox', { name: 'Cidade ou destino' })).toBeVisible();
  await page.goto('/reservas');
  await expect(page).toHaveURL(/\/acesso\?next=/);
  await expect(page.getByText('Bom ter você de volta', { exact: true })).toBeVisible();
  await page.goto('/perfil');
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nome completo', exact: true }).fill('Cliente de teste local');
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByLabel('Confirmar senha', { exact: true }).fill(password);
  await page.screenshot({ path: resolve(evidence, 'cadastro.png'), fullPage: true, mask: [page.getByLabel('Senha', { exact: true }), page.getByLabel('Confirmar senha', { exact: true })] });
  await page.getByRole('button', { name: 'Criar conta', exact: true }).click();
  await expect(page.getByText(email, { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(evidence, 'perfil.png') });
  await page.getByRole('button', { name: 'Sair da conta', exact: true }).click();
  await expect(page.getByText('Navegando como visitante', { exact: true })).toBeVisible();
  await page.goto('/favoritos');
  await expect(page).toHaveURL(/\/acesso\?next=/);
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill('senha-errada-local');
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('E-mail ou senha incorretos.', { exact: true })).toBeVisible();
  await page.screenshot({ path: resolve(evidence, 'login-error.png') });
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page.getByText('Seus favoritos aparecerão aqui.', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Reservas' }).click();
  await expect(page.getByText('Suas reservas aparecerão aqui.', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Perfil' }).click();
  await page.getByRole('button', { name: 'Sair da conta', exact: true }).click();
  const catalog = await (await request.get('/api/v1/imoveis?per_page=1')).json();
  const propertyId = catalog.data[0].id as number;
  await page.goto(`/imovel/${propertyId}`);
  await page.getByRole('button', { name: 'Reservar', exact: true }).click();
  await expect(page.getByText('Bom ter você de volta', { exact: true })).toBeVisible();
  await page.getByRole('textbox', { name: 'E-mail', exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Entrar', exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/imovel/${propertyId}$`));
  await expect(page.getByText('O checkout será disponibilizado na próxima etapa.', { exact: false })).toBeVisible();
  expect(errors).toEqual([]);
});
