<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);require __DIR__.'/bootstrap.php';
use App\Core\Database;use App\Models\AsaasWebhookEvento;use App\Services\AsaasWebhookService;
$db=Database::getConnection();if($db->query('SELECT current_database()')->fetchColumn()!=='alugfacil_dev')throw new RuntimeException('Testes permitidos somente em alugfacil_dev.');
$prefix='codex_suite_'.bin2hex(random_bytes(4));$reservationIds=[];$results=[];
$assert=function(bool $ok,string $name)use(&$results){$results[$name]=$ok;if(!$ok)throw new RuntimeException('Falhou: '.$name);};
$snapshot=function(int$id)use($db){$s=$db->prepare('SELECT status_reserva,status_pagamento,versao_status FROM reservas WHERE id=:id');$s->execute(['id'=>$id]);return$s->fetch();};$protected=[2=>$snapshot(2),5=>$snapshot(5)];
$makeReservation=function(string$status='aguardando_pagamento')use($db,$prefix,&$reservationIds){$base=$db->query('SELECT usuario_id,proprietario_id,chacara_id,valor_diaria FROM reservas ORDER BY id LIMIT 1')->fetch();$pid=$prefix.'_pay_'.count($reservationIds);$s=$db->prepare("INSERT INTO reservas(usuario_id,proprietario_id,chacara_id,data_inicio,data_fim,quantidade_diarias,valor_diaria,valor_total,status_reserva,status_pagamento,id_cobranca_asaas,expira_em) VALUES(:u,:p,:c,CURRENT_DATE+1000,CURRENT_DATE+1001,1,:diaria,:diaria,:status,'pendente',:pid,CURRENT_TIMESTAMP+interval '1 day') RETURNING id");$s->execute(['u'=>$base['usuario_id'],'p'=>$base['proprietario_id'],'c'=>$base['chacara_id'],'diaria'=>$base['valor_diaria'],'status'=>$status,'pid'=>$pid]);$id=(int)$s->fetchColumn();$reservationIds[]=$id;return['id'=>$id,'payment'=>$pid,'value'=>(float)$base['valor_diaria']];};
$queue=function(string$type,array$r,array$over=[])use($prefix){static$n=0;$p=['id'=>$prefix.'_event_'.++$n,'event'=>$type,'payment'=>array_merge(['id'=>$r['payment'],'externalReference'=>'reserva_'.$r['id'],'value'=>$r['value'],'billingType'=>'PIX'],$over)];$json=json_encode($p,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$received=(new AsaasWebhookEvento())->receber($p,$json);return[(int)$received['event']['id'],$p];};
try{
 $r=$makeReservation();[$eid,$payload]=$queue('PAYMENT_CONFIRMED',$r);$svc=new AsaasWebhookService($db);$assert($svc->processarPorId($eid)==='processado','confirmacao consistente');$row=$db->query('SELECT status_reserva,status_pagamento FROM reservas WHERE id='.(int)$r['id'])->fetch();$assert($row['status_reserva']==='confirmada'&&$row['status_pagamento']==='pago','reserva e pagamento confirmados');$hist=(int)$db->query('SELECT COUNT(*) FROM historico_status_reservas WHERE reserva_id='.(int)$r['id'])->fetchColumn();$assert($svc->processarPorId($eid)==='ignorado','segunda execucao idempotente');$assert((int)$db->query('SELECT COUNT(*) FROM historico_status_reservas WHERE reserva_id='.(int)$r['id'])->fetchColumn()===$hist,'historico nao duplicado');
 foreach(['expirada','cancelada','finalizada']as$status){$late=$makeReservation($status);[$id]=$queue('PAYMENT_RECEIVED',$late);$assert($svc->processarPorId($id)==='divergente','pagamento tardio '.$status);$state=$db->query('SELECT status_reserva,status_pagamento,divergencia_pagamento FROM reservas WHERE id='.(int)$late['id'])->fetch();$assert($state['status_reserva']===$status&&$state['status_pagamento']==='pago'&&(bool)$state['divergencia_pagamento'],'sem reativacao '.$status);}
 $bad=$makeReservation();[$id]=$queue('PAYMENT_CONFIRMED',$bad,['value'=>$bad['value']+1]);$assert($svc->processarPorId($id)==='divergente','valor divergente');$assert($db->query('SELECT status_reserva FROM reservas WHERE id='.(int)$bad['id'])->fetchColumn()==='aguardando_pagamento','valor nao confirma');
 $bad=$makeReservation();[$id]=$queue('PAYMENT_CONFIRMED',$bad,['externalReference'=>'reserva_999999']);$assert($svc->processarPorId($id)==='divergente','external reference divergente');
 $rev=$makeReservation();foreach(['PAYMENT_REFUNDED','PAYMENT_CHARGEBACK_REQUESTED']as$type){[$id]=$queue($type,$rev);$assert($svc->processarPorId($id)==='divergente',$type.' conciliacao');}
 $unk=$makeReservation();[$id]=$queue('PAYMENT_FUTURE_UNKNOWN',$unk);$assert($svc->processarPorId($id)==='ignorado','evento desconhecido ignorado');
 $assert($snapshot(2)===$protected[2]&&$snapshot(5)===$protected[5],'reservas protegidas intactas');
 foreach($results as$name=>$ok)echo 'PASS '.$name.PHP_EOL;echo 'TOTAL='.count($results).PHP_EOL;
}finally{if($reservationIds){$marks=implode(',',array_fill(0,count($reservationIds),'?'));$db->prepare("DELETE FROM historico_status_reservas WHERE reserva_id IN ($marks)")->execute($reservationIds);$db->prepare("DELETE FROM pagamentos WHERE reserva_id IN ($marks)")->execute($reservationIds);$db->prepare("DELETE FROM reservas WHERE id IN ($marks)")->execute($reservationIds);}$db->prepare('DELETE FROM asaas_webhook_eventos WHERE asaas_event_id LIKE :p')->execute(['p'=>$prefix.'%']);}
