<?php
declare(strict_types=1);
require dirname(__DIR__).'/scripts/bootstrap.php';
use App\Core\Database;use App\Services\PrecificacaoReservaService;
$db=Database::getConnection();$dbName=(string)$db->query('SELECT current_database()')->fetchColumn();if($dbName!=='alugfacil_dev')throw new RuntimeException('Verificacao permitida somente em alugfacil_dev.');echo 'DB='.$dbName.PHP_EOL;echo 'TABLES='.$db->query("SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")->fetchColumn().PHP_EOL;$ok=0;$test=function(bool$c,string$n)use(&$ok){if(!$c)throw new RuntimeException('FALHOU: '.$n);echo "OK $n\n";$ok++;};
$protected=[];foreach([2,5]as$id){$s=$db->prepare('SELECT status_reserva,status_pagamento,id_cobranca_asaas FROM reservas WHERE id=?');$s->execute([$id]);$protected[$id]=$s->fetch();}
$db->beginTransaction();try{$admin=(int)$db->query("SELECT id FROM usuarios WHERE tipo_usuario='admin' ORDER BY id LIMIT 1")->fetchColumn();$v=(int)$db->query('SELECT COALESCE(MAX(versao),0)+1000 FROM configuracoes_financeiras')->fetchColumn();$db->exec('UPDATE configuracoes_financeiras SET vigencia_fim=CURRENT_TIMESTAMP WHERE vigencia_fim IS NULL');$s=$db->prepare('INSERT INTO configuracoes_financeiras(taxa_plataforma_percentual_bps,taxa_plataforma_fixa_centavos,precificacao_ativa,versao,criado_por_admin_id) VALUES(1000,250,true,?,?) RETURNING id');$s->execute([$v,$admin]);$cfg=(int)$s->fetchColumn();$s=$db->prepare("INSERT INTO taxas_meios_pagamento(configuracao_financeira_id,forma_pagamento,quantidade_parcelas,percentual_gateway_bps,taxa_fixa_gateway_centavos,margem_seguranca_bps,ativo) VALUES(?,'PIX',1,299,49,0,true),(?,'CREDIT_CARD',3,399,79,20,true)");$s->execute([$cfg,$cfg]);$svc=new PrecificacaoReservaService($db);$r=$svc->cotar(100000,1,'PIX',1);$test($r['valor_liquido_proprietario_centavos']===100000,'liquido do proprietario preservado');$test($r['taxa_plataforma_centavos']===10250,'taxa percentual e fixa da plataforma');$test($r['valor_total_cliente_centavos']-$r['taxa_gateway_estimada_centavos']>=110250,'gross-up cobre destino');$test($r['valor_total_cliente_centavos']===110250||($r['valor_total_cliente_centavos']-1)-PrecificacaoReservaService::ceilBps($r['valor_total_cliente_centavos']-1,299)-49<110250,'total minimo em centavos');$test($svc->cotar(100000,1,'CREDIT_CARD',3)['quantidade_parcelas']===3,'cartao parcelado usa configuracao correspondente');try{$svc->cotar(100000,1,'CREDIT_CARD',2);$test(false,'parcela inexistente recusada');}catch(RuntimeException){$test(true,'parcela inexistente recusada');}try{PrecificacaoReservaService::ceilBps(100,10000);$test(false,'percentual >= 100 recusado');}catch(RuntimeException){$test(true,'percentual >= 100 recusado');}$test(PrecificacaoReservaService::ceilBps(1,1)===1,'arredondamento para cima');$db->rollBack();}catch(Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}
foreach($protected as$id=>$before){$s=$db->prepare('SELECT status_reserva,status_pagamento,id_cobranca_asaas FROM reservas WHERE id=?');$s->execute([$id]);$test($s->fetch()===$before,'reserva protegida #'.$id.' preservada');}
$test((int)$db->query("SELECT count(*) FROM reservas WHERE origem_precificacao='legado' AND taxa_plataforma_centavos=0 AND taxa_gateway_estimada_centavos=0")->fetchColumn()>0,'backfill legado sem taxas');echo "TOTAL_OK=$ok\n";
$rm=new App\Models\Reserva();$rm->resumoAdministrativo();$pid=(int)$db->query('SELECT id FROM proprietarios ORDER BY id LIMIT 1')->fetchColumn();if($pid){$rm->resumoPorProprietario($pid);$rm->faturamentoPorProprietario($pid,date('Y-m-d',strtotime('-1 year')),date('Y-m-d',strtotime('+2 years')));}$test(true,'consultas financeiras dos paineis executam');
$test((int)$db->query("SELECT count(*) FROM usuarios WHERE email LIKE 'smoke051_%@localhost.test'")->fetchColumn()===0,'zero usuarios temporarios smoke 05.1');
$test((int)$db->query('SELECT count(*) FROM pagamentos p LEFT JOIN reservas r ON r.id=p.reserva_id WHERE r.id IS NULL')->fetchColumn()===0,'zero pagamentos orfaos');
$test((int)$db->query('SELECT count(*) FROM historico_status_reservas h LEFT JOIN reservas r ON r.id=h.reserva_id WHERE r.id IS NULL')->fetchColumn()===0,'zero historicos de reserva orfaos');
$test((int)$db->query('SELECT count(*) FROM cotacoes_reserva q LEFT JOIN usuarios u ON u.id=q.usuario_id LEFT JOIN chacaras c ON c.id=q.chacara_id WHERE u.id IS NULL OR c.id IS NULL')->fetchColumn()===0,'zero cotacoes orfas');
