<?php
declare(strict_types=1);require dirname(__DIR__).'/scripts/bootstrap.php';
use App\Core\Database;use App\Services\AsaasClientInterface;use App\Services\AsaasSubcontaService;use App\Services\AsaasTimeoutException;
final class TimeoutClient implements AsaasClientInterface{public int $calls=0;public function criarSubconta(array$p):array{$this->calls++;throw new AsaasTimeoutException('timeout fake');}public function listarSubcontas(array$f):array{return['data'=>[]];}public function consultarSubconta(string$i):array{return[];}public function verificarContaRaiz():array{return[];}}
$db=Database::getConnection();if($db->query('SELECT current_database()')->fetchColumn()!=='alugfacil_dev')throw new RuntimeException('Banco invalido.');putenv('APP_ENV=development');putenv('ASAAS_BASE_URL=https://api-sandbox.asaas.com/v3');putenv('ASAAS_API_KEY=fake-only-in-memory');putenv('ASAAS_ENABLE_SUBACCOUNT_CREATION=true');putenv('ASAAS_ALLOW_SANDBOX_MUTATIONS=true');putenv('ASAAS_SUBACCOUNT_MODEL=NON_BAAS');
$tag=bin2hex(random_bytes(4));$email="failure-$tag@localhost.test";$uid=0;$pid=0;$checks=[];
try{$s=$db->prepare("INSERT INTO usuarios(nome,email,senha_hash,tipo_usuario,status) VALUES('Teste Falha',:e,'x','proprietario','ativo') RETURNING id");$s->execute(['e'=>$email]);$uid=(int)$s->fetchColumn();$s=$db->prepare("INSERT INTO proprietarios(usuario_id,nome,email,status) VALUES(:u,'Teste Falha',:e,'ativo') RETURNING id");$s->execute(['u'=>$uid,'e'=>$email]);$pid=(int)$s->fetchColumn();$db->prepare("INSERT INTO proprietario_dados_financeiros(proprietario_id,tipo_pessoa,cpf_cnpj,nome_razao_social,data_nascimento,renda_faturamento_mensal_centavos,celular,email_financeiro,cep,endereco,numero,bairro,cidade,estado,dados_completos) VALUES(:p,'PF','11144477735','Teste Falha','1990-01-01',100000,'11999998888',:e,'01001000','Rua Teste','1','Centro','Sao Paulo','SP',TRUE)")->execute(['p'=>$pid,'e'=>$email]);$db->prepare("INSERT INTO aceites_financeiros_proprietarios(proprietario_id,tipo_aceite,versao_documento,texto_hash) VALUES(:p,'ONBOARDING_ASAAS_NON_BAAS','teste',:h)")->execute(['p'=>$pid,'h'=>AsaasSubcontaService::aceiteHash()]);$c=new TimeoutClient();$svc=new AsaasSubcontaService($c,$db);try{$svc->criar($pid,$uid,'Teste controlado',true);}catch(Throwable){}$row=$db->query('SELECT * FROM asaas_subcontas WHERE proprietario_id='.(int)$pid)->fetch();$checks['timeout_conciliacao']=$row['status_local']==='conciliacao_manual';$checks['request_hash_preservado']=strlen((string)$row['request_hash'])===64;$before=$c->calls;$again=$svc->criar($pid,$uid,'Segunda tentativa',true);$checks['segunda_tentativa_sem_post']=$c->calls===$before&&$again['id']===$row['id'];$checks['um_registro']=$db->query('SELECT count(1)=1 FROM asaas_subcontas WHERE proprietario_id='.(int)$pid)->fetchColumn();$checks['historico_sem_duplicar']=$db->query('SELECT count(1)=2 FROM historico_asaas_subcontas WHERE proprietario_id='.(int)$pid)->fetchColumn();foreach($checks as$n=>$ok)echo($ok?'[OK] ':'[FALHA] ').$n.PHP_EOL;
}finally{if($pid){$db->prepare('DELETE FROM historico_asaas_subcontas WHERE proprietario_id=:p')->execute(['p'=>$pid]);$db->prepare('DELETE FROM asaas_subcontas WHERE proprietario_id=:p')->execute(['p'=>$pid]);$db->prepare('DELETE FROM aceites_financeiros_proprietarios WHERE proprietario_id=:p')->execute(['p'=>$pid]);$db->prepare('DELETE FROM proprietario_dados_financeiros WHERE proprietario_id=:p')->execute(['p'=>$pid]);$db->prepare('DELETE FROM proprietarios WHERE id=:p')->execute(['p'=>$pid]);}if($uid)$db->prepare('DELETE FROM usuarios WHERE id=:u')->execute(['u'=>$uid]);}
exit(in_array(false,$checks,true)?1:0);
