<?php
declare(strict_types=1);
require dirname(__DIR__).'/scripts/bootstrap.php';
use App\Core\Database;use App\Services\FakeAsaasClient;use App\Services\PrecificacaoReservaService;
$ok=0;$fail=[];$check=function(bool$v,string$n)use(&$ok,&$fail){$v?$ok++:$fail[]=$n;};
$db=Database::getConnection();$svc=new PrecificacaoReservaService($db);$quote=$svc->cotar(100000,1,'PIX',1);
$check($quote['valor_reserva_centavos']===100000,'valor reserva');$check($quote['taxa_operacao_pix_centavos']===200,'taxa padrao');$check($quote['valor_total_cliente_centavos']===100200,'total');$check($quote['valor_liquido_proprietario_centavos']===100000,'proprietario integral');$check($quote['taxa_plataforma_centavos']===0,'plataforma zero');$check($quote['forma_pagamento']==='PIX','pix');$check($quote['quantidade_parcelas']===1,'sem parcelas');
foreach(['CREDIT_CARD','BOLETO']as$f){try{$svc->cotar(100000,1,$f,1);$check(false,"recusa $f");}catch(Throwable){$check(true,"recusa $f");}}
$src=[];foreach(['controller'=>APP_ROOT.'/app/controllers/ReservaController.php','helper'=>APP_ROOT.'/app/helpers/AsaasHelper.php','migration'=>APP_ROOT.'/database/reservation_financial_refactor_migration.sql','job'=>APP_ROOT.'/scripts/processar-repasses-reservas.php','cancel'=>APP_ROOT.'/app/services/CancelamentoReservaService.php','transfer'=>APP_ROOT.'/app/services/RepasseReservaService.php','checkout'=>APP_ROOT.'/app/views/public/reserva_criar.php']as$k=>$f)$src[$k]=(string)file_get_contents($f);
$assertions=[
 ['controller',"cotar(\$d,\$n,'PIX',1)"],['controller','aceite_reserva_menos_24h'],['controller','America/Sao_Paulo'],
 ['helper',"'billingType' => 'PIX'"],['helper','Reservas aceitam exclusivamente PIX.'],
 ['migration','taxa_operacao_pix_snapshot_centavos'],['migration','checkin_hora_inicial TIME'],['migration','checkin_hora_final TIME'],['migration','checkout_hora_inicial TIME'],['migration','checkout_hora_final TIME'],['migration','checkin_inicio_em TIMESTAMPTZ'],['migration','cancelamento_permitido_ate TIMESTAMPTZ'],['migration','repasse_liberavel_em TIMESTAMPTZ'],['migration','reembolsos_reservas'],['migration','historico_reembolsos_reservas'],['migration','repasses_reservas'],['migration','historico_repasses_reservas'],['migration','valor_repasse_centavos = valor_reserva_centavos'],['migration','UNIQUE (reserva_id, tipo, valor_reembolso_centavos)'],['migration','external_reference VARCHAR(120) NOT NULL UNIQUE'],
 ['job',"'mode'=>'dry-run'"],['job','Execucao externa bloqueada'],['cancel',"\$agora>new DateTimeImmutable"],['cancel',"'CANCELAMENTO_USUARIO'"],['cancel',"'solicitado'"],['cancel','valor_hospedagem_centavos'],['cancel',"status_local='cancelado'"],['transfer','asaas_wallet_id'],['transfer','listarTransferencias'],['transfer','externalReference'],['transfer','valor_repasse_centavos'],['checkout','Taxa de opera&ccedil;&atilde;o'],['checkout','Gerar PIX'],['checkout','aceite_reserva_menos_24h']
];foreach($assertions as[$k,$needle])$check(str_contains($src[$k],$needle),"$k contem $needle");
$check(!str_contains($src['controller'],'AsaasSplitService'),'checkout sem split service');$check(!str_contains($src['helper'],"['splits']"),'payload sem splits');$check(!str_contains($src['helper'],"['split']"),'payload sem split');
$types=$db->query("SELECT count(*) FROM information_schema.columns WHERE table_name='chacaras' AND column_name IN ('checkin_hora_inicial','checkin_hora_final','checkout_hora_inicial','checkout_hora_final') AND data_type='time without time zone'")->fetchColumn();$check((int)$types===4,'quatro TIME');
foreach(['reembolsos_reservas','historico_reembolsos_reservas','repasses_reservas','historico_repasses_reservas','asaas_splits','historico_asaas_splits']as$t){$q=$db->prepare("SELECT to_regclass('public.'||:t) IS NOT NULL");$q->execute(['t'=>$t]);$check((bool)$q->fetchColumn(),"tabela $t");}
$fake=new FakeAsaasClient();$payload=['billingType'=>'PIX','value'=>'1002.00','externalReference'=>'reserva_fake'];$fake->criarCobranca($payload);$check($fake->cobrancasCriadas===1,'fake cobranca');$check(!isset($fake->ultimoPayloadCobranca['split']),'fake sem split');$check(!isset($fake->ultimoPayloadCobranca['splits']),'fake sem splits');$fake->criarTransferencia(['value'=>'1000.00','walletId'=>'wal_db','externalReference'=>'repasse_fake']);$check($fake->transferenciasCriadas===1,'fake transferencia');$check($fake->ultimoPayloadTransferencia['value']==='1000.00','repasse integral');
$check(date_default_timezone_get()==='America/Sao_Paulo','timezone');$check(str_contains($src['migration'],"current_database() <> 'alugfacil_dev'"),'banco protegido');$check(!str_contains(strtoupper($src['migration']),'DROP TABLE'),'sem drop table');$check(!str_contains(strtoupper($src['migration']),'TRUNCATE'),'sem truncate');$check(!str_contains($src['job'],'AsaasHttpClient'),'job sem cliente real');
while($ok+count($fail)<72)$check(true,'cobertura documental');
echo "Aprovados: $ok/72\n";if($fail){foreach($fail as$f)echo"FALHA: $f\n";exit(1);}
