<?php
$label = static fn (string $valor): string => ucfirst(str_replace('_', ' ', $valor));
$transicoes = ['pendente' => ['aprovada' => 'Aprovar', 'rejeitada' => 'Rejeitar'], 'aprovada' => ['bloqueada' => 'Bloquear'], 'bloqueada' => ['aprovada' => 'Desbloquear', 'pendente' => 'Devolver para analise'], 'rejeitada' => ['pendente' => 'Reabrir analise']];
?>
<div class="panel-page-heading"><div><span>Administracao</span><h1><?= e($chacara['nome']) ?></h1><p>Dados, fotos e decis&atilde;o administrativa do im&oacute;vel.</p></div><a class="btn btn-outline" href="<?= url('/admin/chacaras') ?>">Voltar</a></div>
<section class="admin-detail-grid"><article class="panel-card"><div class="panel-card-heading"><h2>Dados do im&oacute;vel</h2></div><dl class="admin-detail-list">
<div><dt>Propriet&aacute;rio</dt><dd><?= e($chacara['proprietario_nome']) ?></dd></div><div><dt>Status do propriet&aacute;rio</dt><dd><?= e($label($chacara['proprietario_status'])) ?></dd></div><div><dt>Cidade</dt><dd><?= e($chacara['cidade']) ?></dd></div><div><dt>Endere&ccedil;o</dt><dd><?= e($chacara['endereco']) ?></dd></div><div><dt>Aprova&ccedil;&atilde;o</dt><dd><span class="status-pill"><?= e($label($chacara['status_aprovacao'])) ?></span></dd></div><div><dt>Disponibilidade</dt><dd><?= e($label($chacara['status_operacional'])) ?></dd></div></dl>
<form class="admin-status-action" method="post" action="<?= url('/admin/chacaras/' . (int) $chacara['id'] . '/status') ?>"><?= csrf_field() ?><label>Motivo <input type="text" name="motivo" value="<?= e($chacara['motivo_status'] ?? '') ?>"></label><?php foreach ($transicoes[$chacara['status_aprovacao']] ?? [] as $novo => $rotulo): ?><button class="btn <?= in_array($novo, ['bloqueada','rejeitada'], true) ? 'btn-danger' : 'btn-primary' ?>" name="status" value="<?= e($novo) ?>" type="submit"><?= e($rotulo) ?></button><?php endforeach; ?></form></article>
<article class="panel-card"><div class="panel-card-heading"><h2>Fotos</h2></div><?php if (!$fotos): ?><p>Nenhuma foto cadastrada.</p><?php else: ?><div class="owner-photo-grid"><?php foreach ($fotos as $foto): ?><img src="<?= asset($foto['caminho_foto']) ?>" alt="Foto de <?= e($chacara['nome']) ?>"><?php endforeach; ?></div><?php endif; ?></article></section>
