<?php
$rows=$config['taxas']??[];$configured=[];
foreach($rows as$row)$configured[$row['forma_pagamento'].'-'.(int)$row['quantidade_parcelas']]=true;
$defaults=[['PIX',1],['CREDIT_CARD',1],['CREDIT_CARD',2],['CREDIT_CARD',3]];
foreach($defaults as[$forma,$parcelas])if(!isset($configured[$forma.'-'.$parcelas]))$rows[]=['forma_pagamento'=>$forma,'quantidade_parcelas'=>$parcelas,'percentual_gateway_bps'=>0,'taxa_fixa_gateway_centavos'=>0,'margem_seguranca_bps'=>0,'ativo'=>false];
?>
<header class="panel-page-heading"><div><span>Administra&ccedil;&atilde;o</span><h1>Configura&ccedil;&otilde;es financeiras</h1><p>Taxas em basis points e valores fixos em centavos. Nenhuma taxa comercial &eacute; presumida.</p></div></header>
<section class="panel-card"><form method="post" action="<?= url('/admin/configuracoes-financeiras') ?>"><?= csrf_field() ?>
<div class="panel-form-grid"><label>Taxa da plataforma (bps)<input type="number" name="plataforma_bps" min="0" max="9999" value="<?= e((string)($config['taxa_plataforma_percentual_bps']??0)) ?>" required></label><label>Taxa fixa da plataforma (centavos)<input type="number" name="plataforma_fixa" min="0" value="<?= e((string)($config['taxa_plataforma_fixa_centavos']??0)) ?>" required></label><label><input type="checkbox" name="precificacao_ativa" <?= !empty($config['precificacao_ativa'])?'checked':'' ?>> Precifica&ccedil;&atilde;o ativa</label></div>
<h2>Meios de pagamento</h2><div class="responsive-table"><table class="panel-table"><thead><tr><th>Forma</th><th>Parcelas</th><th>Gateway (bps)</th><th>Fixa (centavos)</th><th>Margem (bps)</th><th>Ativa</th></tr></thead><tbody><?php foreach($rows as$k=>$t):?><tr><td><select name="forma_pagamento[<?= $k ?>]"><option <?= $t['forma_pagamento']==='PIX'?'selected':'' ?>>PIX</option><option <?= $t['forma_pagamento']==='CREDIT_CARD'?'selected':'' ?>>CREDIT_CARD</option><option <?= $t['forma_pagamento']==='BOLETO'?'selected':'' ?>>BOLETO</option></select></td><td><input type="number" name="parcelas[<?= $k ?>]" min="1" max="24" value="<?= (int)$t['quantidade_parcelas'] ?>"></td><td><input type="number" name="gateway_bps[<?= $k ?>]" min="0" max="9999" value="<?= (int)$t['percentual_gateway_bps'] ?>"></td><td><input type="number" name="gateway_fixa[<?= $k ?>]" min="0" value="<?= (int)$t['taxa_fixa_gateway_centavos'] ?>"></td><td><input type="number" name="margem_bps[<?= $k ?>]" min="0" max="9999" value="<?= (int)$t['margem_seguranca_bps'] ?>"></td><td><input type="checkbox" name="taxa_ativa[<?= $k ?>]" <?= !empty($t['ativo'])?'checked':'' ?>></td></tr><?php endforeach;?></tbody></table></div>
<label>Motivo da altera&ccedil;&atilde;o<textarea name="motivo" maxlength="500" required></textarea></label><button class="btn btn-primary" type="submit">Salvar nova vers&atilde;o</button></form></section>
<section class="panel-card"><h2>Hist&oacute;rico imut&aacute;vel</h2><div class="responsive-table"><table class="panel-table"><thead><tr><th>Vers&atilde;o</th><th>Administrador</th><th>Motivo</th><th>Data</th></tr></thead><tbody><?php foreach($historico as$h):?><tr><td><?= (int)$h['versao'] ?></td><td><?= e($h['administrador_nome']) ?></td><td><?= e($h['motivo']) ?></td><td><?= e(date('d/m/Y H:i',strtotime($h['criado_em']))) ?></td></tr><?php endforeach;?></tbody></table></div></section>
