<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Auth;use App\Core\Controller;use App\Models\FinanceiroProprietario;use App\Services\AsaasHttpClient;use App\Services\AsaasSubcontaService;use Throwable;
final class FinancialOnboardingController extends Controller
{
 public function owner():void{$p=Auth::requireProprietarioAutenticado();$m=new FinanceiroProprietario();$this->view('proprietario/financeiro/index',['title'=>'Recebimentos','panelRole'=>'proprietario','proprietario'=>$p,'dados'=>$m->buscar((int)$p['id']),'aceite'=>$m->aceiteVigente((int)$p['id']),'subconta'=>$m->subconta((int)$p['id']),'termo'=>AsaasSubcontaService::ACEITE_TEXTO],'panel');}
 public function save():void{$p=Auth::requireProprietarioOperacional();verify_csrf();try{$d=AsaasSubcontaService::validarDados($_POST);$existing=(new FinanceiroProprietario())->subconta((int)$p['id']);if($existing&&$existing['asaas_account_id']&&!hash_equals((string)($p['cpf']??''),$d['cpf_cnpj']))throw new \RuntimeException('CPF/CNPJ nao pode ser alterado depois da criacao sem revisao administrativa.');(new FinanceiroProprietario())->salvar((int)$p['id'],$d,(int)Auth::user()['id']);flash('success','Dados financeiros validados e salvos.');}catch(Throwable$e){flash('error',$e->getMessage());}$this->redirect('/proprietario/recebimentos');}
 public function accept():void{$p=Auth::requireProprietarioOperacional();verify_csrf();if(($_POST['aceite_explicito']??'')!=='1'){flash('error','Confirme explicitamente todas as condicoes.');$this->redirect('/proprietario/recebimentos');}$m=new FinanceiroProprietario();if(!$m->buscar((int)$p['id'])){flash('error','Complete os dados antes do aceite.');$this->redirect('/proprietario/recebimentos');}$m->aceitar((int)$p['id'],AsaasSubcontaService::aceiteHash(),$_SERVER['REMOTE_ADDR']??'',$_SERVER['HTTP_USER_AGENT']??'');flash('success','Autorizacao financeira registrada.');$this->redirect('/proprietario/recebimentos');}
 public function admin():void{Auth::requireRole('admin');$status=trim((string)($_GET['status']??''));$this->view('admin/financeiro/index',['title'=>'Onboarding financeiro','panelRole'=>'admin','items'=>(new FinanceiroProprietario())->listarAdmin($status),'status'=>$status],'panel');}
 public function details(string$id):void{Auth::requireRole('admin');$pid=$this->id($id);$m=new FinanceiroProprietario();$s=\App\Core\Database::getConnection()->prepare('SELECT p.*,u.status usuario_status FROM proprietarios p JOIN usuarios u ON u.id=p.usuario_id WHERE p.id=:p');$s->execute(['p'=>$pid]);$p=$s->fetch();if(!$p){http_response_code(404);exit;}$h=\App\Core\Database::getConnection()->prepare('SELECT * FROM historico_asaas_subcontas WHERE proprietario_id=:p ORDER BY criado_em DESC');$h->execute(['p'=>$pid]);$this->view('admin/financeiro/show',['title'=>'Detalhe financeiro','panelRole'=>'admin','proprietario'=>$p,'dados'=>$m->buscar($pid),'aceite'=>$m->aceiteVigente($pid),'subconta'=>$m->subconta($pid),'historico'=>$h->fetchAll()],'panel');}
 public function action(string$id):void{Auth::requireRole('admin');verify_csrf();$pid=$this->id($id);$motivo=trim((string)($_POST['motivo']??''));if($motivo===''){flash('error','Motivo obrigatorio.');$this->redirect('/admin/onboarding-financeiro/'.$pid);}$service=new AsaasSubcontaService(new AsaasHttpClient());try{$acao=(string)($_POST['acao']??'');if($acao==='criar')$service->criar($pid,(int)Auth::user()['id'],$motivo,($_POST['confirmacao']??'')==='CRIAR SANDBOX');elseif($acao==='sincronizar')$service->sincronizar($pid,(int)Auth::user()['id'],$motivo);elseif($acao==='conciliar'){if(!$service->conciliar($pid,(int)Auth::user()['id'],$motivo))throw new \RuntimeException('Conciliacao sem correspondencia inequivoca.');}else throw new \RuntimeException('Acao invalida.');flash('success','Acao financeira concluida.');}catch(Throwable$e){flash('error',$e->getMessage());}$this->redirect('/admin/onboarding-financeiro/'.$pid);}
 private function id(string$v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($id===false){http_response_code(404);exit;}return(int)$id;}
}
