<?php
declare(strict_types=1);
namespace App\Models;
use App\Core\Model;use PDO;use RuntimeException;use Throwable;
final class ConfiguracaoFinanceira extends Model
{
 public function atual():?array{$c=$this->db->query('SELECT * FROM configuracoes_financeiras WHERE vigencia_fim IS NULL ORDER BY versao DESC LIMIT 1')->fetch();if(!$c)return null;$s=$this->db->prepare('SELECT * FROM taxas_meios_pagamento WHERE configuracao_financeira_id=:id ORDER BY forma_pagamento,quantidade_parcelas');$s->execute(['id'=>$c['id']]);$c['taxas']=$s->fetchAll();return$c;}
 public function historico():array{return$this->db->query('SELECT h.*,u.nome administrador_nome FROM historico_configuracoes_financeiras h JOIN usuarios u ON u.id=h.administrador_id ORDER BY h.criado_em DESC,h.id DESC LIMIT 50')->fetchAll();}
 public function salvar(array$c,array$taxas,int$admin,string$motivo):int{$motivo=trim($motivo);if($motivo==='')throw new RuntimeException('Informe o motivo da alteracao.');foreach(['taxa_plataforma_percentual_bps','taxa_plataforma_fixa_centavos']as$k)if(!isset($c[$k])||(int)$c[$k]<0)throw new RuntimeException('Taxa da plataforma invalida.');if((int)$c['taxa_plataforma_percentual_bps']>=10000)throw new RuntimeException('Percentual da plataforma invalido.');if(!$taxas)throw new RuntimeException('Configure ao menos um meio de pagamento.');
  $this->db->beginTransaction();try{$anterior=$this->atual();$v=(int)$this->db->query('SELECT COALESCE(MAX(versao),0)+1 FROM configuracoes_financeiras')->fetchColumn();$this->db->exec('UPDATE configuracoes_financeiras SET vigencia_fim=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE vigencia_fim IS NULL');$s=$this->db->prepare('INSERT INTO configuracoes_financeiras(taxa_plataforma_percentual_bps,taxa_plataforma_fixa_centavos,precificacao_ativa,versao,criado_por_admin_id) VALUES(:bps,:fixa,:ativa,:v,:a) RETURNING id');$s->execute(['bps'=>$c['taxa_plataforma_percentual_bps'],'fixa'=>$c['taxa_plataforma_fixa_centavos'],'ativa'=>$c['precificacao_ativa'],'v'=>$v,'a'=>$admin]);$id=(int)$s->fetchColumn();
  $i=$this->db->prepare('INSERT INTO taxas_meios_pagamento(configuracao_financeira_id,forma_pagamento,quantidade_parcelas,percentual_gateway_bps,taxa_fixa_gateway_centavos,margem_seguranca_bps,ativo) VALUES(:c,:f,:p,:bps,:fixa,:m,:ativo)');foreach($taxas as$t){if(!in_array($t['forma_pagamento'],['PIX','CREDIT_CARD','BOLETO'],true)||(int)$t['quantidade_parcelas']<1||(int)$t['percentual_gateway_bps']<0||(int)$t['margem_seguranca_bps']<0||(int)$t['percentual_gateway_bps']+(int)$t['margem_seguranca_bps']>=10000||(int)$t['taxa_fixa_gateway_centavos']<0)throw new RuntimeException('Configuracao de pagamento invalida.');$i->execute(['c'=>$id,'f'=>$t['forma_pagamento'],'p'=>$t['quantidade_parcelas'],'bps'=>$t['percentual_gateway_bps'],'fixa'=>$t['taxa_fixa_gateway_centavos'],'m'=>$t['margem_seguranca_bps'],'ativo'=>$t['ativo']]);}
  $nova=$this->atual();$this->db->prepare('INSERT INTO historico_configuracoes_financeiras(configuracao_anterior,configuracao_nova,administrador_id,motivo,versao) VALUES(CAST(:a AS JSONB),CAST(:n AS JSONB),:admin,:m,:v)')->execute(['a'=>$anterior?json_encode($anterior):null,'n'=>json_encode($nova),'admin'=>$admin,'m'=>mb_substr($motivo,0,500),'v'=>$v]);$this->db->commit();return$v;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
