<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use DateTimeImmutable;use PDO;use RuntimeException;use Throwable;
final class AsaasSubcontaService
{
 public const ACEITE_TEXTO='Autorizo o envio dos dados cadastrais ao Asaas e a criacao de uma conta Asaas vinculada. Estou ciente de que receberei comunicacoes do Asaas, acessarei a conta diretamente no Asaas e o recebimento depende de aprovacao cadastral. Texto operacional sujeito a revisao juridica.';
 public function __construct(private AsaasClientInterface $client,private ?PDO $db=null){$this->db??=Database::getConnection();}
 public static function validarDados(array $in):array
 {
  $d=[];foreach(['tipo_pessoa','cpf_cnpj','nome_razao_social','nome_fantasia','data_nascimento','tipo_empresa','telefone','celular','email_financeiro','cep','endereco','numero','complemento','bairro','cidade','estado']as$k)$d[$k]=trim((string)($in[$k]??''));
  $d['tipo_pessoa']=strtoupper($d['tipo_pessoa']);$d['cpf_cnpj']=preg_replace('/\D+/','',$d['cpf_cnpj'])??'';$d['cep']=preg_replace('/\D+/','',$d['cep'])??'';$d['telefone']=preg_replace('/\D+/','',$d['telefone'])??'';$d['celular']=preg_replace('/\D+/','',$d['celular'])??'';$d['estado']=strtoupper($d['estado']);
  $raw=(string)($in['renda_faturamento_mensal']??'');$raw=str_replace(['.',' '],'',$raw);$raw=str_replace(',','.',$raw);if(!is_numeric($raw))throw new RuntimeException('Informe renda ou faturamento valido.');$d['renda_faturamento_mensal_centavos']=(int)round((float)$raw*100);
  if(!in_array($d['tipo_pessoa'],['PF','PJ'],true))throw new RuntimeException('Tipo de pessoa invalido.');if(!self::documentoValido($d['cpf_cnpj'],$d['tipo_pessoa']))throw new RuntimeException($d['tipo_pessoa']==='PF'?'CPF invalido.':'CNPJ invalido.');
  if($d['nome_razao_social']===''||!filter_var($d['email_financeiro'],FILTER_VALIDATE_EMAIL)||strlen($d['cep'])!==8||strlen($d['celular'])<10||strlen($d['celular'])>11||$d['endereco']===''||$d['numero']===''||$d['bairro']===''||$d['cidade']===''||!preg_match('/^[A-Z]{2}$/',$d['estado'])||$d['renda_faturamento_mensal_centavos']<=0)throw new RuntimeException('Dados financeiros incompletos ou invalidos.');
  if($d['telefone']!==''&&(strlen($d['telefone'])<10||strlen($d['telefone'])>11))throw new RuntimeException('Telefone invalido.');
  if($d['tipo_pessoa']==='PF'){if(!self::dataNascimentoValida($d['data_nascimento']))throw new RuntimeException('Data de nascimento invalida ou incompativel.');$d['tipo_empresa']='';}else{if(!in_array($d['tipo_empresa'],['MEI','LIMITED','INDIVIDUAL','ASSOCIATION'],true))throw new RuntimeException('Tipo de empresa invalido.');$d['data_nascimento']='';}
  return$d;
 }
 public static function aceiteHash():string{return hash('sha256',self::ACEITE_TEXTO);}
 public function payload(array $d):array{$p=['name'=>$d['nome_razao_social'],'email'=>$d['email_financeiro'],'loginEmail'=>$d['email_financeiro'],'cpfCnpj'=>$d['cpf_cnpj'],'phone'=>$d['telefone']?:null,'mobilePhone'=>$d['celular'],'incomeValue'=>$d['renda_faturamento_mensal_centavos']/100,'address'=>$d['endereco'],'addressNumber'=>$d['numero'],'complement'=>$d['complemento']?:null,'province'=>$d['bairro'],'postalCode'=>$d['cep']];if($d['tipo_pessoa']==='PF')$p['birthDate']=$d['data_nascimento'];else$p['companyType']=$d['tipo_empresa'];return array_filter($p,static fn($v)=>$v!==null&&$v!=='');}
 public function criar(int $pid,int $adminId,string $motivo,bool $confirmado):array
 {
  $this->validarMutacao($confirmado);if(trim($motivo)==='')throw new RuntimeException('Motivo administrativo obrigatorio.');
  $this->db->beginTransaction();try{$s=$this->db->prepare('SELECT p.*,u.status usuario_status,d.* FROM proprietarios p JOIN usuarios u ON u.id=p.usuario_id JOIN proprietario_dados_financeiros d ON d.proprietario_id=p.id WHERE p.id=:p FOR UPDATE OF p');$s->execute(['p'=>$pid]);$d=$s->fetch();if(!$d||$d['usuario_status']!=='ativo')throw new RuntimeException('Conta do proprietario nao esta ativa ou possui dados incompletos.');$d=self::validarDados($d+['renda_faturamento_mensal'=>$d['renda_faturamento_mensal_centavos']/100]);if(!$this->aceiteVigente($pid))throw new RuntimeException('Aceite financeiro vigente obrigatorio.');$payload=$this->payload($d);$hash=hash('sha256',json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$existing=$this->selectSubconta($pid,true);if($existing){$this->db->commit();return$existing;}$sid=bin2hex(random_bytes(16));$i=$this->db->prepare("INSERT INTO asaas_subcontas(proprietario_id,ambiente,modelo,email_cadastro,status_local,request_hash,solicitacao_id,quantidade_tentativas,solicitada_em) VALUES(:p,'sandbox','NON_BAAS',:e,'criando',:h,:sid,1,CURRENT_TIMESTAMP) RETURNING id");$i->execute(['p'=>$pid,'e'=>$d['email_financeiro'],'h'=>$hash,'sid'=>$sid]);$id=(int)$i->fetchColumn();$this->historico($id,$pid,null,'criando','administrador',$motivo,$adminId);$this->db->commit();
  try{$response=$this->client->criarSubconta($payload);$account=trim((string)($response['id']??$response['accountId']??''));$wallet=trim((string)($response['walletId']??''));unset($response['apiKey']);if($account===''||$wallet==='')throw new AsaasTimeoutException('Resposta incompleta; resultado externo desconhecido.');$this->db->beginTransaction();$this->db->prepare("UPDATE asaas_subcontas SET asaas_account_id=:a,asaas_wallet_id=:w,status_local='aguardando_ativacao',criada_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id AND status_local='criando'")->execute(['a'=>$account,'w'=>$wallet,'id'=>$id]);$this->historico($id,$pid,'criando','aguardando_ativacao','sistema','Subconta criada; ativacao e analise pendentes.',$adminId);$this->db->commit();return$this->selectSubconta($pid)??[];
  }catch(AsaasTimeoutException $e){$this->falhar($id,$pid,'conciliacao_manual','TIMEOUT_DESCONHECIDO','Resultado externo desconhecido; nova criacao bloqueada.');throw new RuntimeException('Resultado externo desconhecido. Registro enviado para conciliacao manual.');}catch(Throwable $e){$this->falhar($id,$pid,'erro','CRIACAO_RECUSADA',$this->sanitizar($e->getMessage()));throw new RuntimeException($this->sanitizar($e->getMessage()));}
  }catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 public function sincronizar(int $pid,?int $adminId=null,string $motivo='Sincronizacao solicitada'):string{$row=$this->selectSubconta($pid);if(!$row||empty($row['asaas_account_id']))throw new RuntimeException('Subconta vinculada nao encontrada.');$r=$this->client->consultarSubconta($row['asaas_account_id']);$external=strtoupper((string)($r['status']??$r['accountStatus']??''));$new=match($external){'APPROVED','ACTIVE'=>'aprovada','PENDING','AWAITING_APPROVAL'=>'em_analise','REJECTED'=>'rejeitada','BLOCKED'=>'bloqueada',default=>$row['status_local']};if($row['status_local']==='aprovada'&&$new==='em_analise')$new='aprovada';$this->db->beginTransaction();if($new!==$row['status_local']){$this->db->prepare('UPDATE asaas_subcontas SET status_local=:s,status_cadastral_asaas=:e,ultima_sincronizacao_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id')->execute(['s'=>$new,'e'=>$external?:null,'id'=>$row['id']]);$this->historico((int)$row['id'],$pid,$row['status_local'],$new,'sincronizacao',$motivo,$adminId);}else$this->db->prepare('UPDATE asaas_subcontas SET status_cadastral_asaas=:e,ultima_sincronizacao_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id')->execute(['e'=>$external?:null,'id'=>$row['id']]);$this->db->commit();return$new;}
 public function conciliar(int $pid,int $adminId,string $motivo):bool{$row=$this->selectSubconta($pid);if(!$row||$row['status_local']!=='conciliacao_manual')return false;$s=$this->db->prepare('SELECT cpf_cnpj,email_financeiro FROM proprietario_dados_financeiros WHERE proprietario_id=:p');$s->execute(['p'=>$pid]);$d=$s->fetch();$result=$this->client->listarSubcontas(['cpfCnpj'=>$d['cpf_cnpj'],'email'=>$d['email_financeiro'],'limit'=>10]);$matches=array_values(array_filter($result['data']??[],fn($x)=>($x['cpfCnpj']??'')===$d['cpf_cnpj']&&strcasecmp((string)($x['email']??''),$d['email_financeiro'])===0&&!empty($x['id'])&&!empty($x['walletId'])));if(count($matches)!==1)return false;$x=$matches[0];$this->db->beginTransaction();$this->db->prepare("UPDATE asaas_subcontas SET asaas_account_id=:a,asaas_wallet_id=:w,status_local='aguardando_ativacao',criada_em=COALESCE(criada_em,CURRENT_TIMESTAMP),atualizado_em=CURRENT_TIMESTAMP WHERE id=:id")->execute(['a'=>$x['id'],'w'=>$x['walletId'],'id'=>$row['id']]);$this->historico((int)$row['id'],$pid,'conciliacao_manual','aguardando_ativacao','conciliacao',$motivo,$adminId);$this->db->commit();return true;}
 public function financeiramenteHabilitado(int $pid):bool{$s=$this->db->prepare("SELECT EXISTS(SELECT 1 FROM proprietarios p JOIN usuarios u ON u.id=p.usuario_id JOIN proprietario_dados_financeiros d ON d.proprietario_id=p.id JOIN asaas_subcontas a ON a.proprietario_id=p.id AND a.ambiente='sandbox' WHERE p.id=:p AND u.status='ativo' AND d.dados_completos AND a.asaas_wallet_id IS NOT NULL AND a.status_local='aprovada' AND EXISTS(SELECT 1 FROM aceites_financeiros_proprietarios x WHERE x.proprietario_id=p.id AND x.tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND x.revogado_em IS NULL))");$s->execute(['p'=>$pid]);return(bool)$s->fetchColumn();}
 private function validarMutacao(bool$c):void{if(!$c||getenv('APP_ENV')==='production'||!str_contains(strtolower((string)getenv('ASAAS_BASE_URL')),'sandbox')||getenv('ASAAS_API_KEY')===''||getenv('ASAAS_ENABLE_SUBACCOUNT_CREATION')!=='true'||getenv('ASAAS_ALLOW_SANDBOX_MUTATIONS')!=='true'||(getenv('ASAAS_SUBACCOUNT_MODEL')?:'NON_BAAS')!=='NON_BAAS')throw new RuntimeException('Criacao Sandbox bloqueada pela configuracao de seguranca.');}
 private function aceiteVigente(int$p):bool{$s=$this->db->prepare("SELECT EXISTS(SELECT 1 FROM aceites_financeiros_proprietarios WHERE proprietario_id=:p AND tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND texto_hash=:h AND revogado_em IS NULL)");$s->execute(['p'=>$p,'h'=>self::aceiteHash()]);return(bool)$s->fetchColumn();}
 private function selectSubconta(int$p,bool$lock=false):?array{$s=$this->db->prepare("SELECT * FROM asaas_subcontas WHERE proprietario_id=:p AND ambiente='sandbox'".($lock?' FOR UPDATE':''));$s->execute(['p'=>$p]);return$s->fetch()?:null;}
 private function historico(int$id,int$p,?string$a,string$n,string$o,string$m,?int$admin):void{$this->db->prepare('INSERT INTO historico_asaas_subcontas(asaas_subconta_id,proprietario_id,status_anterior,status_novo,origem,motivo,administrador_id) VALUES(:id,:p,:a,:n,:o,:m,:u)')->execute(['id'=>$id,'p'=>$p,'a'=>$a,'n'=>$n,'o'=>$o,'m'=>mb_substr($m,0,500),'u'=>$admin]);}
 private function falhar(int$id,int$p,string$status,string$code,string$error):void{$this->db->beginTransaction();$this->db->prepare('UPDATE asaas_subcontas SET status_local=:s,ultimo_codigo_erro=:c,ultimo_erro_sanitizado=:e,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id')->execute(['s'=>$status,'c'=>$code,'e'=>$error,'id'=>$id]);$this->historico($id,$p,'criando',$status,'sistema',$error,null);$this->db->commit();}
 private function sanitizar(string$v):string{foreach([getenv('ASAAS_API_KEY'),getenv('ASAAS_WEBHOOK_TOKEN')]as$x)if(is_string($x)&&$x!=='')$v=str_replace($x,'[REDACTED]',$v);return mb_substr(preg_replace('/[\r\n\t]+/',' ',$v)??'Erro interno.',0,1000);}
 private static function documentoValido(string$d,string$t):bool{$len=$t==='PF'?11:14;if(strlen($d)!==$len||preg_match('/^(\d)\1+$/',$d))return false;if($t==='PF'){$sum=0;for($i=0;$i<9;$i++)$sum+=(int)$d[$i]*(10-$i);$x=($sum*10)%11;if($x===10)$x=0;if($x!==(int)$d[9])return false;$sum=0;for($i=0;$i<10;$i++)$sum+=(int)$d[$i]*(11-$i);$x=($sum*10)%11;if($x===10)$x=0;return$x===(int)$d[10];}$weights=[[5,4,3,2,9,8,7,6,5,4,3,2],[6,5,4,3,2,9,8,7,6,5,4,3,2]];for($digit=12;$digit<14;$digit++){$sum=0;for($i=0;$i<$digit;$i++)$sum+=(int)$d[$i]*$weights[$digit-12][$i];$x=$sum%11;$x=$x<2?0:11-$x;if($x!==(int)$d[$digit])return false;}return true;}
 private static function dataNascimentoValida(string$d):bool{try{$date=new DateTimeImmutable($d);$today=new DateTimeImmutable('today');return$date->format('Y-m-d')===$d&&$date<=$today->modify('-18 years')&&$date>=$today->modify('-120 years');}catch(Throwable){return false;}}
}
