<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use PDO;use RuntimeException;use Throwable;
final class AsaasSubcontaReconciliationService
{
 public function __construct(private AsaasClientInterface $client,private ?PDO$db=null){$this->db??=Database::getConnection();}
 public static function credenciaisRotacionadasConfirmadas():bool{$at=trim((string)getenv('ASAAS_CREDENTIALS_ROTATED_AT'));return getenv('ASAAS_CREDENTIALS_ROTATION_CONFIRMED')==='true'&&preg_match('/^20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}/',$at)===1;}
 public static function mascara(string$v):string{$v=trim($v);if($v==='')return'-';return strlen($v)<=8?str_repeat('*',strlen($v)):substr($v,0,3).str_repeat('*',strlen($v)-6).substr($v,-3);}
 public function candidatos():array{$sql="SELECT p.id proprietario_id,p.usuario_id,d.cpf_cnpj,d.email_financeiro FROM proprietarios p JOIN usuarios u ON u.id=p.usuario_id JOIN proprietario_dados_financeiros d ON d.proprietario_id=p.id WHERE u.status='ativo' AND d.dados_completos AND EXISTS(SELECT 1 FROM aceites_financeiros_proprietarios a WHERE a.proprietario_id=p.id AND a.tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND a.texto_hash=:h AND a.revogado_em IS NULL) AND NOT EXISTS(SELECT 1 FROM asaas_subcontas s WHERE s.proprietario_id=p.id AND s.ambiente='sandbox' AND s.status_local IN ('bloqueada','conciliacao_manual')) ORDER BY p.id";$q=$this->db->prepare($sql);$q->execute(['h'=>AsaasSubcontaService::aceiteHash()]);return$q->fetchAll();}
 public function proprietario(int$id):array{$q=$this->db->prepare("SELECT p.id proprietario_id,p.usuario_id,p.status proprietario_status,u.status usuario_status,d.*,EXISTS(SELECT 1 FROM aceites_financeiros_proprietarios a WHERE a.proprietario_id=p.id AND a.tipo_aceite='ONBOARDING_ASAAS_NON_BAAS' AND a.texto_hash=:h AND a.revogado_em IS NULL) aceite FROM proprietarios p JOIN usuarios u ON u.id=p.usuario_id JOIN proprietario_dados_financeiros d ON d.proprietario_id=p.id WHERE p.id=:p");$q->execute(['p'=>$id,'h'=>AsaasSubcontaService::aceiteHash()]);$r=$q->fetch();if(!$r)throw new RuntimeException('Proprietario nao encontrado ou sem dados financeiros.');return$r;}
 public function consultarCorrespondencias(array$d):array
 {
  $this->validarLeituraRemota();$all=[];foreach([['cpfCnpj'=>$d['cpf_cnpj']],['email'=>$d['email_financeiro']]]as$filter){$offset=0;do{$r=$this->client->listarSubcontas($filter+['limit'=>100,'offset'=>$offset]);foreach(($r['data']??[])as$x)if(is_array($x)&&$this->corresponde($x,$d))$all[(string)($x['id']??hash('sha256',json_encode($x)))]=$x;$offset+=100;$more=(bool)($r['hasMore']??false);}while($more);}
  return array_values($all);
 }
 public function reconciliarExistente(int$pid,array$remote,string$origem='conciliacao'):array
 {
  $d=$this->proprietario($pid);if(!$this->corresponde($remote,$d))throw new RuntimeException('Subconta remota nao corresponde ao proprietario.');$account=trim((string)($remote['id']??$remote['accountId']??''));$wallet=trim((string)($remote['walletId']??''));if($account===''||$wallet==='')throw new RuntimeException('Subconta remota sem account ID ou walletId.');$statusExt=strtoupper((string)($remote['status']??$remote['accountStatus']??'PENDING'));$oper=strtoupper((string)($remote['operationalStatus']??$remote['status']??''));$local=match($statusExt){'APPROVED','ACTIVE'=>'aprovada','REJECTED'=>'rejeitada','BLOCKED'=>'bloqueada',default=>'em_analise'};$hash=hash('sha256',$pid.'|sandbox|'.$account);
  $this->db->beginTransaction();try{$q=$this->db->prepare("SELECT * FROM asaas_subcontas WHERE (proprietario_id=:p AND ambiente='sandbox') OR asaas_account_id=:a OR asaas_wallet_id=:w FOR UPDATE");$q->execute(['p'=>$pid,'a'=>$account,'w'=>$wallet]);$rows=$q->fetchAll();foreach($rows as$x)if((int)$x['proprietario_id']!==$pid)throw new RuntimeException('Account ID ou walletId ja vinculado a outro proprietario.');$existing=$rows[0]??null;if($existing){$this->db->prepare('UPDATE asaas_subcontas SET asaas_account_id=:a,asaas_wallet_id=:w,status_local=:s,status_cadastral_asaas=:c,status_operacional_asaas=:o,ultima_sincronizacao_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id')->execute(['a'=>$account,'w'=>$wallet,'s'=>$local,'c'=>$statusExt?:null,'o'=>$oper?:null,'id'=>$existing['id']]);$id=(int)$existing['id'];if($existing['status_local']!==$local)$this->historico($id,$pid,$existing['status_local'],$local,$origem,'Subconta Sandbox reconciliada.');}else{$q=$this->db->prepare("INSERT INTO asaas_subcontas(proprietario_id,ambiente,modelo,asaas_account_id,asaas_wallet_id,email_cadastro,status_local,status_cadastral_asaas,status_operacional_asaas,request_hash,solicitacao_id,quantidade_tentativas,criada_em,ultima_sincronizacao_em) VALUES(:p,'sandbox','NON_BAAS',:a,:w,:e,:s,:c,:o,:h,:sid,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id");$q->execute(['p'=>$pid,'a'=>$account,'w'=>$wallet,'e'=>$d['email_financeiro'],'s'=>$local,'c'=>$statusExt?:null,'o'=>$oper?:null,'h'=>$hash,'sid'=>'reconcile_'.substr($hash,0,40)]);$id=(int)$q->fetchColumn();$this->historico($id,$pid,null,$local,$origem,'Subconta Sandbox existente reconciliada.');}$q=$this->db->prepare('SELECT * FROM asaas_subcontas WHERE id=:id');$q->execute(['id'=>$id]);$out=$q->fetch();$this->db->commit();return$out;}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}
 }
 public function reconciliar(int$pid,bool$permitirCriacao=false,int$adminId=0):array{$d=$this->proprietario($pid);$matches=$this->consultarCorrespondencias($d);if(count($matches)>1)throw new RuntimeException('Multiplas subcontas correspondentes; conciliacao manual obrigatoria.');if(count($matches)===1)return['resultado'=>'reconciliada','registro'=>$this->reconciliarExistente($pid,$matches[0])];if(!$permitirCriacao)return['resultado'=>'nenhuma_encontrada','registro'=>null];if($adminId<1)throw new RuntimeException('Administrador obrigatorio para criacao.');$row=(new AsaasSubcontaService($this->client,$this->db))->criar($pid,$adminId,'HOMOLOGACAO ALUG FACIL SUBCONTA',true);return['resultado'=>'criada','registro'=>$row];}
 private function validarLeituraRemota():void{if(!self::credenciaisRotacionadasConfirmadas())throw new RuntimeException('Rotacao das credenciais nao comprovada; acesso remoto bloqueado.');if(getenv('APP_ENV')==='production'||rtrim((string)getenv('ASAAS_BASE_URL'),'/')!=='https://api-sandbox.asaas.com/v3'||trim((string)getenv('ASAAS_API_KEY'))==='')throw new RuntimeException('Consulta permitida somente no Sandbox configurado.');}
 private function corresponde(array$x,array$d):bool{$doc=preg_replace('/\D+/','',(string)($x['cpfCnpj']??''))??'';$email=trim((string)($x['email']??$x['loginEmail']??''));return$doc===(string)$d['cpf_cnpj']&&strcasecmp($email,(string)$d['email_financeiro'])===0;}
 private function historico(int$id,int$p,?string$a,string$n,string$o,string$m):void{$this->db->prepare('INSERT INTO historico_asaas_subcontas(asaas_subconta_id,proprietario_id,status_anterior,status_novo,origem,motivo) VALUES(:id,:p,:a,:n,:o,:m)')->execute(['id'=>$id,'p'=>$p,'a'=>$a,'n'=>$n,'o'=>$o,'m'=>$m]);}
}
