<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use PDO;use RuntimeException;use Throwable;
final class RepasseReservaService
{
 public function __construct(private AsaasTransferClientInterface$client,private?PDO$db=null){$this->db??=Database::getConnection();}
 public function processar(int$id,bool$confirmado=false):array
 {$this->db->beginTransaction();try{$q=$this->db->prepare("SELECT rp.*,r.status_reserva,r.status_pagamento,s.asaas_wallet_id,s.modelo,s.status_local subconta_status FROM repasses_reservas rp JOIN reservas r ON r.id=rp.reserva_id LEFT JOIN asaas_subcontas s ON s.proprietario_id=rp.proprietario_id AND s.ambiente='sandbox' WHERE rp.id=:id FOR UPDATE OF rp");$q->execute(['id'=>$id]);$r=$q->fetch();if(!$r)throw new RuntimeException('Repasse nao encontrado.');if($r['status_local']==='concluido'){$this->db->commit();return['idempotente'=>true];}if($r['status_pagamento']!=='pago'||$r['status_reserva']!=='confirmada'||$r['modelo']!=='NON_BAAS'||$r['subconta_status']!=='ativa')throw new RuntimeException('Repasse sem elegibilidade financeira.');if(strtotime((string)$r['repasse_liberavel_em'])>time())throw new RuntimeException('Repasse ainda nao liberado.');$wallet=trim((string)$r['asaas_wallet_id']);if($wallet==='')throw new RuntimeException('Proprietario sem wallet habilitada.');$payload=['value'=>PrecificacaoReservaService::centavosParaDecimal((int)$r['valor_repasse_centavos']),'walletId'=>$wallet,'externalReference'=>$r['external_reference']];if(!$confirmado){$this->db->rollBack();return['dry_run'=>true,'payload'=>$payload];}$existing=$this->client->listarTransferencias(['externalReference'=>$r['external_reference']]);if(!empty($existing['data']))throw new RuntimeException('Transferencia externa preexistente; conciliacao necessaria.');$out=$this->client->criarTransferencia($payload);if(empty($out['id']))throw new AsaasTimeoutException('Resultado ambiguo; POST nao sera repetido.');$this->db->prepare("UPDATE repasses_reservas SET status_local='processando',asaas_transfer_id=:t,status_asaas=:s,tentativa_count=tentativa_count+1,solicitado_em=CURRENT_TIMESTAMP,processando_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id")->execute(['t'=>$out['id'],'s'=>$out['status']??null,'id'=>$id]);$this->db->commit();return['transfer_id'=>$out['id'],'payload'=>$payload];}catch(Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
