<?php $money=static fn(int$v):string=>($v<0?'- ':'').'R$ '.number_format(abs($v)/100,2,',','.'); ?>
<header class="panel-page-heading"><div><span>Programa de afiliados</span><h1>Olá, <?= e($affiliate['nome']) ?></h1><p>Acompanhe suas indicações e seus resultados financeiros.</p></div><span class="status-pill affiliate-status-<?= e($affiliate['status']) ?>"><?= e(ucfirst($affiliate['status'])) ?></span></header>
<section class="metric-grid affiliate-dashboard-grid" aria-label="Indicadores do programa"><?php foreach([['Proprietários indicados',$dashboard['proprietarios'],'Vínculos ativos e históricos'],['Chácaras indicadas',$dashboard['chacaras'],'Pertencentes aos indicados'],['Chácaras com mensalidade',$dashboard['chacaras_mensalidade'],'Configuração financeira existente'],['Mensalidades pagas no mês',$dashboard['pagamentos_mes'],'Pagamentos que geraram comissão'],['Comissão gerada no mês',$money($dashboard['comissao_mes_centavos']),'Valores registrados no ledger'],['Valor em aberto',$money($dashboard['em_aberto_centavos']),'Dentro do período de 7 dias'],['Saldo disponível',$money($dashboard['saldo_disponivel_centavos']),'Após pagamentos e ajustes'],['Total já recebido',$money($dashboard['total_pago_centavos']),'Pagamentos administrativos']] as$card):?><article><span><?= e($card[0]) ?></span><strong><?= e((string)$card[1]) ?></strong><small><?= e($card[2]) ?></small></article><?php endforeach;?></section>
<section class="panel-card affiliate-share-card">
    <div class="panel-card-heading"><div><h2>Divulgação</h2><p>Compartilhe seu código ou o link direto de cadastro.</p></div></div>
    <div class="affiliate-share-grid">
        <div class="affiliate-share-item"><label for="affiliate-code">Seu código de afiliado</label><div class="affiliate-link-row"><input id="affiliate-code" value="<?= e($affiliate['codigo']) ?>" readonly aria-readonly="true"><button class="btn btn-outline" type="button" data-copy-target="affiliate-code">Copiar código</button></div></div>
        <div class="affiliate-share-item"><label for="affiliate-referral-link">Seu link de divulgação</label><div class="affiliate-link-row"><textarea id="affiliate-referral-link" rows="2" readonly aria-readonly="true"><?= e($referralLink) ?></textarea><button class="btn btn-primary" type="button" data-copy-target="affiliate-referral-link">Copiar link</button></div></div>
    </div>
    <p class="affiliate-copy-feedback" data-copy-feedback aria-live="polite"></p>
</section>
<script>document.querySelectorAll('[data-copy-target]').forEach(button=>button.addEventListener('click',async()=>{const input=document.getElementById(button.dataset.copyTarget),feedback=document.querySelector('[data-copy-feedback]');try{await navigator.clipboard.writeText(input.value)}catch(_){input.select();document.execCommand('copy')}feedback.textContent=button.dataset.copyTarget==='affiliate-code'?'Código copiado.':'Link copiado.';}));</script>
