<?php $pixLabels=['cpf'=>'CPF','cnpj'=>'CNPJ','email'=>'E-mail','telefone'=>'Telefone','aleatoria'=>'Aleatória']; ?>
<header class="panel-page-heading"><div><span>Programa de afiliados</span><h1>Meu perfil</h1><p>Dados cadastrais e forma de recebimento.</p></div><span class="status-pill affiliate-status-<?= e($affiliate['status']) ?>"><?= e(ucfirst($affiliate['status'])) ?></span></header>
<section class="panel-card owner-form-card affiliate-profile-card"><div class="panel-card-heading"><div><h2>Dados do afiliado</h2><p>Atualize seus dados de contato, pagamento e acesso.</p></div></div>
<form class="owner-property-form affiliate-form" method="post" action="<?= url('/afiliado/perfil') ?>"><?= csrf_field() ?>
<fieldset class="affiliate-form-section form-full"><legend>Dados protegidos</legend><div class="affiliate-form-grid affiliate-readonly-grid"><label>Código<input value="<?= e($affiliate['codigo']) ?>" readonly aria-readonly="true"></label><label>CPF/CNPJ<input value="<?= e($affiliate['cpf_cnpj']) ?>" readonly aria-readonly="true"></label><label>Status<input value="<?= e(ucfirst($affiliate['status'])) ?>" readonly aria-readonly="true"></label></div><small>Código, documento, status e percentual são administrados pelo Alug Fácil.</small></fieldset>
<fieldset class="affiliate-form-section form-full"><legend>Dados pessoais e contato</legend><div class="affiliate-form-grid"><label>Nome<input name="nome" maxlength="150" autocomplete="name" required value="<?= e(old('nome',$affiliate['nome'])) ?>"></label><label>Telefone<input type="tel" name="telefone" maxlength="30" autocomplete="tel" required value="<?= e(old('telefone',$affiliate['telefone'])) ?>"></label><label>E-mail<input type="email" name="email" maxlength="180" autocomplete="email" required value="<?= e(old('email',$affiliate['email'])) ?>"></label></div></fieldset>
<fieldset class="affiliate-form-section form-full"><legend>Dados para pagamento</legend><div class="affiliate-form-grid"><label>Tipo da chave PIX<select name="tipo_chave_pix" required><?php foreach($pixTypes as$type):?><option value="<?= e($type) ?>" <?= old('tipo_chave_pix',$affiliate['tipo_chave_pix'])===$type?'selected':'' ?>><?= e($pixLabels[$type]??$type) ?></option><?php endforeach;?></select></label><label>Chave PIX<input name="chave_pix" maxlength="150" required value="<?= e(old('chave_pix',$affiliate['chave_pix'])) ?>"></label><label>Banco<input name="banco" maxlength="120" autocomplete="organization" value="<?= e(old('banco',$affiliate['banco']??'')) ?>"></label></div></fieldset>
<fieldset class="affiliate-form-section form-full"><legend>Alterar senha <small>(opcional)</small></legend><div class="affiliate-form-grid affiliate-password-fields"><label>Senha atual<input type="password" name="senha_atual" autocomplete="current-password"></label><label>Nova senha<input type="password" name="nova_senha" minlength="8" autocomplete="new-password"></label><label>Confirmar nova senha<input type="password" name="nova_senha_confirmacao" minlength="8" autocomplete="new-password"></label></div></fieldset>
<div class="form-actions affiliate-form-actions"><button class="btn btn-primary" type="submit">Salvar perfil</button></div></form></section>
