<?php $fs=static fn(string$s):string=>ucfirst(str_replace('_',' ',$s));$mc=static fn(int$v):string=>'R$ '.number_format($v/100,2,',','.');?>
<section class="profile-page reservation-page"><div class="container"><div class="confirmation-card"><div class="confirmation-content"><span class="profile-kicker">Reserva #<?= (int)$reserva['id'] ?></span><h1>Reserva criada com sucesso</h1><p class="confirmation-message">A reserva ser&aacute; confirmada ap&oacute;s a confirma&ccedil;&atilde;o do pagamento pelo Asaas.</p><dl class="confirmation-details">
<div><dt>Im&oacute;vel</dt><dd><?= e($reserva['chacara_nome']) ?></dd></div><div><dt>Per&iacute;odo</dt><dd><?= e(date('d/m/Y',strtotime($reserva['data_inicio']))) ?> a <?= e(date('d/m/Y',strtotime($reserva['data_fim']))) ?></dd></div>
<div><dt>Di&aacute;rias</dt><dd><?= e($mc((int)$reserva['valor_hospedagem_centavos'])) ?></dd></div><div><dt>Taxa de opera&ccedil;&atilde;o</dt><dd><?= e($mc((int)$reserva['taxa_operacao_pix_snapshot_centavos'])) ?></dd></div><div class="confirmation-total"><dt>Total</dt><dd><?= e($mc((int)$reserva['valor_total_cliente_centavos'])) ?></dd></div><div><dt>Pagamento</dt><dd><?= e($reserva['forma_pagamento']) ?></dd></div><div><dt>Status</dt><dd><span class="status-pill"><?= e($fs($reserva['status_reserva'])) ?></span></dd></div>
<?php if(($reserva['modalidade']??'integral')==='integral'&&!empty($reserva['cancelamento_permitido_ate'])):?><div><dt>Cancelamento permitido at&eacute;</dt><dd><?= e(date('d/m/Y H:i',strtotime($reserva['cancelamento_permitido_ate']))) ?></dd></div><?php endif;?></dl>
<?php if(($reserva['modalidade']??'integral')==='entrada_parcelamento'):?>
<p class="reservation-note">Ap&oacute;s a confirma&ccedil;&atilde;o da entrada, n&atilde;o h&aacute; cancelamento volunt&aacute;rio. A &uacute;ltima parcela deve estar integralmente paga em D&minus;5, sem toler&acirc;ncia adicional.</p>
<?php if(!empty($obrigacoes)):?>
<h2>Pagamentos da reserva</h2>
<div style="overflow-x:auto"><table class="table"><thead><tr><th>Pagamento</th><th>Valor</th><th>Vencimento</th><th>Limite definitivo</th><th>Situa&ccedil;&atilde;o</th><th></th></tr></thead><tbody>
<?php foreach($obrigacoes as $obrigacao):?>
<tr><td><?= $obrigacao['numero']===0?'Entrada':'Parcela '.(int)$obrigacao['numero'] ?></td><td><?= e($mc((int)$obrigacao['total_centavos'])) ?></td><td><?= e((new DateTimeImmutable($obrigacao['vencimento_em']))->format('d/m/Y H:i')) ?></td><td><?= !empty($obrigacao['cancelamento_em'])?e((new DateTimeImmutable($obrigacao['cancelamento_em']))->format('d/m/Y H:i')):'&mdash;' ?></td><td><?= e($fs($obrigacao['situacao'])) ?></td><td>
<?php if(in_array($reserva['status_reserva'],['confirmada','em_andamento'],true)&&$obrigacao['estado']==='pendente'&&!empty($obrigacao['invoice_url'])&&!empty($obrigacao['cancelamento_em'])&&strtotime($obrigacao['cancelamento_em'])>time()):?><a href="<?= url('/reserva/confirmacao/'.(int)$reserva['id'].'?parcela='.(int)$obrigacao['numero']) ?>">Abrir pagamento</a><?php endif;?>
</td></tr><?php endforeach;?></tbody></table></div>
<p>Nas parcelas intermedi&aacute;rias, a toler&acirc;ncia de cinco dias come&ccedil;a no vencimento seguinte. Cada parcela &eacute; acompanhada separadamente.</p>
<?php endif;endif;?>
<p class="reservation-note">Em cancelamentos volunt&aacute;rios sujeitos &agrave; pol&iacute;tica da reserva, a taxa de opera&ccedil;&atilde;o n&atilde;o integra o valor reembols&aacute;vel, ressalvadas as hip&oacute;teses previstas em lei.</p>
<?php if($reserva['status_reserva']==='aguardando_pagamento'):?>
<p><?= !empty($reserva['entrada_boleto_emitida_em'])?'Prazo para pagamento da entrada':'Prazo para gerar o pagamento' ?>: <?= e((new DateTimeImmutable($reserva['expira_em']))->format('d/m/Y H:i:s')) ?>.</p>
<?php if(($reserva['modalidade']??'integral')==='entrada_parcelamento'&&$reserva['forma_pagamento']==='BOLETO'):?><p>A entrada vence em um dia corrido ap&oacute;s a emiss&atilde;o. As datas ficam bloqueadas nesse prazo. Sem pagamento confirmado, a reserva ser&aacute; encerrada automaticamente. O cronograma ser&aacute; criado somente ap&oacute;s o pagamento da entrada.</p><?php endif;?>
<?php if(!empty($pagador['proprietario_id'])):?><p>O pagamento usa o documento de seus <a href="<?= url('/proprietario/dados-cadastrais') ?>">Dados Cadastrais</a>.</p>
<?php elseif(empty($pagador['cpf_cnpj'])):?><form method="post" action="<?= url('/reserva/'.(int)$reserva['id'].'/documento-pagador') ?>"><?= csrf_field() ?><label>Tipo de pessoa<select name="tipo_pessoa"><option value="PF">Pessoa f&iacute;sica</option><option value="PJ">Pessoa jur&iacute;dica</option></select></label><label>CPF/CNPJ do pagador<input name="cpf_cnpj" inputmode="numeric" maxlength="18" required></label><button class="btn btn-outline">Salvar documento</button></form><?php endif;?>
<?php endif;?>
<?php if(empty($pagamento)&&!empty($reserva['pix_qr_code_base64'])):?><img src="data:image/png;base64,<?= e($reserva['pix_qr_code_base64']) ?>" alt="QR Code PIX" width="220" height="220"><?php endif;?>
<?php if(empty($pagamento)&&!empty($reserva['pix_copia_cola'])):?><label>C&oacute;digo PIX copia e cola</label><textarea readonly rows="3"><?= e($reserva['pix_copia_cola']) ?></textarea><?php endif;?>
<?php require APP_ROOT.'/app/views/public/reserva_pagamento.php'; ?>
<?php if($reserva['status_reserva']==='aguardando_pagamento'&&strtotime($reserva['expira_em'])>time()&&empty($reserva['id_cobranca_asaas'])&&empty($pagamento)):?><form method="post" action="<?= url('/reserva/'.(int)$reserva['id'].'/gerar-pagamento') ?>"><?= csrf_field() ?>
<?php if(($reserva['modalidade']??'integral')==='entrada_parcelamento'&&$reserva['forma_pagamento']==='CREDIT_CARD'):?><label><input type="checkbox" name="autorizar_recorrencia" value="1" required> Autorizo cobrar cada parcela contratada no cart&atilde;o utilizado na entrada, a partir do respectivo vencimento. Informarei os dados do cart&atilde;o na p&aacute;gina segura do Asaas.</label><?php endif;?>
<button class="btn btn-book">Gerar pagamento</button></form><?php endif;?><a class="confirmation-back" href="<?= url('/cliente/historico') ?>">Ver minhas reservas</a></div></div></div></section>
