<?php $foto=trim(str_replace('\\','/',(string)($chacara['foto']??'')));$arquivo=$foto!==''?APP_ROOT.'/public/'.ltrim($foto,'/'):'';$foto=$arquivo!==''&&is_file($arquivo)?url('/'.ltrim($foto,'/')):asset('img/chacara-'.((((int)$chacara['id']-1)%6)+1).'.jpg');$moeda=static fn(int$v):string=>'R$ '.number_format($v/100,2,',','.');$diaria=App\Services\PrecificacaoReservaService::decimalParaCentavos((string)$chacara['valor_diaria']);$calendarioId='reservation-range-'.(int)$chacara['id'];?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.css">
<section class="profile-page reservation-page"><div class="container"><nav class="profile-breadcrumb"><a href="<?= url('/') ?>">In&iacute;cio</a><span>&rsaquo;</span><a href="<?= url('/chacara/'.(int)$chacara['id']) ?>"><?= e($chacara['nome']) ?></a><span>&rsaquo;</span><strong>Reservar</strong></nav>
<header class="profile-heading reservation-heading"><div><span class="profile-kicker">Fluxo de reserva</span><h1>Reserve <?= e($chacara['nome']) ?></h1><p>Pagamento exclusivamente por PIX.</p></div></header>
<div class="reservation-layout"><article class="reservation-property-card"><img src="<?= e($foto) ?>" alt="Foto principal"><div><span class="section-kicker">Im&oacute;vel selecionado</span><h2><?= e($chacara['nome']) ?></h2><div class="booking-price"><strong><?= e($moeda($diaria)) ?></strong><small>/ di&aacute;ria</small></div></div></article>
<form class="reservation-form" action="<?= url('/reserva/criar/'.(int)$chacara['id']) ?>" method="post"><?= csrf_field() ?><?php if($cotacaoId):?><input type="hidden" name="cotacao_id" value="<?= e($cotacaoId) ?>"><?php endif;?><input type="hidden" name="forma_pagamento" value="PIX"><input type="hidden" name="quantidade_parcelas" value="1">
<div class="reservation-calendar" data-reservation-calendar data-min-date="<?= e($minDataInicio) ?>" data-max-date="<?= e($maxDataFim) ?>" data-locked="<?= $cotacao?'true':'false' ?>">
<div class="reservation-range-field" data-reservation-enhanced hidden><label for="<?= e($calendarioId) ?>">Per&iacute;odo da reserva</label><div class="reservation-range-control"><input id="<?= e($calendarioId) ?>" type="text" data-reservation-range placeholder="Selecione entrada e sa&iacute;da" aria-describedby="<?= e($calendarioId) ?>-help" readonly><?php if(!$cotacao):?><button type="button" class="reservation-calendar-clear" data-reservation-clear>Limpar</button><?php endif;?></div><p id="<?= e($calendarioId) ?>-help" class="reservation-calendar-help" data-reservation-calendar-status aria-live="polite">Selecione a entrada e depois a sa&iacute;da. A sa&iacute;da n&atilde;o conta como di&aacute;ria.</p><div class="reservation-calendar-legend" aria-label="Legenda do calend&aacute;rio"><span><i class="is-available"></i>Dispon&iacute;vel</span><span><i class="is-unavailable"></i>Indispon&iacute;vel</span><span><i class="is-checkout"></i>Somente sa&iacute;da</span></div></div>
<div class="reservation-form-grid" data-reservation-native><label>Data inicial<input type="date" name="data_inicio" value="<?= e($dataInicio) ?>" min="<?= e($minDataInicio) ?>" max="<?= e($maxDataFim) ?>" required <?= $cotacao?'readonly':'' ?>></label><label>Data final<input type="date" name="data_fim" value="<?= e($dataFim) ?>" min="<?= e($minDataInicio) ?>" max="<?= e($maxDataFim) ?>" required <?= $cotacao?'readonly':'' ?>></label></div>
<script type="application/json" data-reservation-unavailable><?= json_encode($datasIndisponiveis,JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script></div>
<div class="reservation-summary"><div><span>Di&aacute;rias</span><strong><?= $cotacao?e($moeda((int)$cotacao['valor_hospedagem_centavos'])):$quantidadeDiarias ?></strong></div><?php if($cotacao):?><div><span>Taxa de opera&ccedil;&atilde;o</span><strong><?= e($moeda((int)$cotacao['taxa_operacao_pix_centavos'])) ?></strong></div><?php endif;?><div class="reservation-total"><span>Total</span><strong><?= e($moeda((int)$valorTotal)) ?></strong></div></div>
<p class="reservation-note">Em cancelamentos volunt&aacute;rios sujeitos &agrave; pol&iacute;tica da reserva, a taxa de opera&ccedil;&atilde;o n&atilde;o integra o valor reembols&aacute;vel, ressalvadas as hip&oacute;teses previstas em lei.</p>
<?php if($cotacao&&!empty($menos24h)):?><div class="payment-empty">Esta reserva est&aacute; dentro da janela de 24 horas e n&atilde;o possui cancelamento volunt&aacute;rio com reembolso ap&oacute;s a confirma&ccedil;&atilde;o, ressalvadas hip&oacute;teses legais.</div><label><input type="checkbox" name="aceite_reserva_menos_24h" value="1" required> Li e aceito esta condi&ccedil;&atilde;o.</label><?php endif;?>
<button class="btn btn-book" type="submit"><?= $cotacao?'Gerar PIX':'Calcular total' ?></button></form></div></div></section>
<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/flatpickr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/l10n/pt.js"></script>
