<?php
$money=static fn(int$value):string=>($value<0?'- ':'').'R$ '.number_format(abs($value)/100,2,',','.');
$date=static fn(?string$value,bool$time=false):string=>$value?date($time?'d/m/Y H:i':'d/m/Y',strtotime($value)):'-';
$effectiveStatus=static function(array$c):string{if($c['estornada_em']!==null)return$c['status']==='PAGA'?'PAGA_COM_ESTORNO':'ESTORNADA';if(in_array($c['status'],['PAGA','CANCELADA','ESTORNADA'],true))return$c['status'];return strtotime($c['disponivel_em'])<=time()?'DISPONIVEL':'EM_ABERTO';};
$labels=['EM_ABERTO'=>'Em aberto','DISPONIVEL'=>'Disponível','PAGA'=>'Paga','PAGA_COM_ESTORNO'=>'Paga · estorno compensável','CANCELADA'=>'Cancelada','ESTORNADA'=>'Estornada'];
?>
<header class="panel-page-heading"><div><span>Administração · Afiliados</span><h1><?= e($affiliate['nome']) ?></h1><p>Código <?= e($affiliate['codigo']) ?> · Comissões, ajustes e pagamentos.</p></div><div class="heading-actions"><span class="status-pill affiliate-status-<?= e($affiliate['status']) ?>"><?= e(ucfirst($affiliate['status'])) ?></span><a class="btn btn-outline" href="<?= url('/admin/afiliados') ?>">Voltar</a></div></header>
<section class="metric-grid affiliate-finance-summary" aria-label="Resumo financeiro"><article><span>Em aberto</span><strong><?= e($money((int)$summary['em_aberto_centavos'])) ?></strong><small>Dentro dos 7 dias</small></article><article><span>Saldo disponível</span><strong><?= e($money((int)$summary['saldo_disponivel_centavos'])) ?></strong><small>Já considera ajustes</small></article><article><span>Total pago</span><strong><?= e($money((int)$summary['total_pago_centavos'])) ?></strong><small>Registrado manualmente</small></article><article><span>Ajustes</span><strong class="<?= (int)$summary['ajustes_centavos']<0?'affiliate-negative-value':'' ?>"><?= e($money((int)$summary['ajustes_centavos'])) ?></strong><small>Estornos após repasse</small></article></section>

<section class="panel-card owner-form-card affiliate-payment-card"><div class="panel-card-heading"><div><h2>Registrar pagamento</h2><p>Saldo disponível: <strong><?= e($money((int)$summary['saldo_disponivel_centavos'])) ?></strong>. A alocação usa as comissões mais antigas primeiro.</p></div></div>
<form class="owner-property-form" method="post" action="<?= url('/admin/afiliados/'.(int)$affiliate['id'].'/pagamentos') ?>"><?= csrf_field() ?><label>Valor (R$)<input name="valor" inputmode="decimal" required value="<?= e(old('valor','')) ?>"></label><label>Data do pagamento<input type="date" name="data_pagamento" required value="<?= e(old('data_pagamento',date('Y-m-d'))) ?>"></label><label class="form-full">Referência opcional<input name="referencia" maxlength="180" value="<?= e(old('referencia','')) ?>" placeholder="PIX, transferência ou protocolo"></label><label class="form-full">Observação opcional<textarea name="observacao" maxlength="1000" rows="4"><?= e(old('observacao','')) ?></textarea></label><div class="form-actions"><button class="btn btn-primary" type="submit">Registrar pagamento</button></div></form></section>

<div class="affiliate-finance-stack"><section class="panel-card"><div class="panel-card-heading"><h2>Histórico de comissões</h2></div><?php if(!$commissions):?><div class="empty-preview"><span aria-hidden="true">&#36;</span><div><strong>Nenhuma comissão gerada</strong><p>As comissões confirmadas aparecerão aqui.</p></div></div><?php else:?><div class="responsive-table"><table class="panel-table"><thead><tr><th scope="col">Confirmação</th><th scope="col">Chácara</th><th scope="col">Pagamento Asaas</th><th scope="col">Base</th><th scope="col">%</th><th scope="col">Comissão</th><th scope="col">Alocado</th><th scope="col">Liberação</th><th scope="col">Status</th></tr></thead><tbody><?php foreach($commissions as$c):$status=$effectiveStatus($c);?><tr><td><?= e($date($c['confirmado_em'],true)) ?></td><td><?= e($c['chacara_nome']) ?></td><td><?= e($c['asaas_payment_id']) ?></td><td><?= e($money((int)$c['valor_base_centavos'])) ?></td><td><?= e(number_format(((int)$c['percentual_bps'])/100,2,',','.').'%') ?></td><td><strong><?= e($money((int)$c['valor_comissao_centavos'])) ?></strong></td><td><?= e($money((int)$c['alocado_centavos'])) ?></td><td><?= e($date($c['disponivel_em'],true)) ?></td><td><span class="status-pill affiliate-commission-status affiliate-commission-<?= e(strtolower($status)) ?>"><?= e($labels[$status]??$status) ?></span></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<section class="panel-card"><div class="panel-card-heading"><h2>Pagamentos registrados</h2></div><?php if(!$payments):?><div class="empty-preview"><span aria-hidden="true">&#10003;</span><div><strong>Nenhum pagamento registrado</strong><p>Pagamentos manuais aparecerão aqui após o registro.</p></div></div><?php else:?><div class="responsive-table"><table class="panel-table"><thead><tr><th scope="col">Data</th><th scope="col">Valor</th><th scope="col">Referência</th><th scope="col">Observação</th><th scope="col">Administrador</th><th scope="col">Registro</th></tr></thead><tbody><?php foreach($payments as$p):?><tr><td><?= e($date($p['data_pagamento'])) ?></td><td><strong><?= e($money((int)$p['valor_centavos'])) ?></strong></td><td><?= e($p['referencia']??'-') ?></td><td><?= e($p['observacao']??'-') ?></td><td><?= e($p['administrador_nome']??'Administrador removido') ?></td><td><?= e($date($p['registrado_em'],true)) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<section class="panel-card"><div class="panel-card-heading"><h2>Alocações FIFO</h2></div><?php if(!$allocations):?><div class="empty-preview"><span aria-hidden="true">&#8644;</span><div><strong>Nenhuma alocação registrada</strong><p>As liquidações de comissões aparecerão aqui.</p></div></div><?php else:?><div class="responsive-table"><table class="panel-table"><thead><tr><th scope="col">Pagamento</th><th scope="col">Referência</th><th scope="col">Chácara</th><th scope="col">Origem Asaas</th><th scope="col">Valor liquidado</th></tr></thead><tbody><?php foreach($allocations as$a):?><tr><td><?= e($date($a['data_pagamento'])) ?></td><td><?= e($a['referencia']??'-') ?></td><td><?= e($a['chacara_nome']) ?></td><td><?= e($a['asaas_payment_id']) ?></td><td><?= e($money((int)$a['valor_centavos'])) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>

<section class="panel-card"><div class="panel-card-heading"><h2>Ajustes por estorno</h2></div><?php if(!$adjustments):?><div class="empty-preview"><span aria-hidden="true">&#8722;</span><div><strong>Nenhum ajuste negativo</strong><p>Estornos posteriores a repasses aparecerão aqui.</p></div></div><?php else:?><div class="responsive-table"><table class="panel-table"><thead><tr><th scope="col">Data</th><th scope="col">Chácara</th><th scope="col">Pagamento Asaas</th><th scope="col">Valor</th><th scope="col">Motivo</th></tr></thead><tbody><?php foreach($adjustments as$a):?><tr><td><?= e($date($a['criado_em'],true)) ?></td><td><?= e($a['chacara_nome']) ?></td><td><?= e($a['asaas_payment_id']) ?></td><td class="affiliate-negative-value"><?= e($money((int)$a['valor_centavos'])) ?></td><td><?= e($a['motivo']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>
